import { describe, it, expect } from 'vitest';
import { generateBaseStylesCss } from '../src/generators/base-styles-css.js';
import type { C2bConfig } from '../src/types.js';

const config: C2bConfig = {
  prefix: 'design-system',
  srcDir: 'src/styles',
  themeDir: 'dist/wp',
  bundleFonts: false,
  themeable: false,
  tokens: {
    fontFamily: {
      inter: { value: 'Inter, sans-serif', name: 'Inter', slug: 'inter' },
    },
    fontSize: {
      small: { value: '1rem', name: 'Small', slug: 'small' },
      medium: { value: '1.125rem', name: 'Medium', slug: 'medium' },
    },
    fontWeight: {
      bold: { value: '700' },
    },
  },
  baseStyles: {
    body: {
      fontFamily: 'inter',
      fontSize: 'medium',
      fontWeight: '400',
      lineHeight: '1.6',
    },
    heading: {
      fontFamily: 'inter',
    },
    h1: { fontSize: '4.5rem', fontWeight: '500' },
    h2: { fontSize: '3rem', fontWeight: '500' },
    h6: { fontSize: '1.45rem', fontWeight: '500', fontStyle: 'italic' },
    caption: { fontSize: 'small', fontStyle: 'italic', fontWeight: '300' },
  },
};

describe('generateBaseStylesCss', () => {
  it('returns null when no baseStyles', () => {
    const result = generateBaseStylesCss({ ...config, baseStyles: undefined });
    expect(result).toBeNull();
  });

  it('includes auto-generated header', () => {
    const result = generateBaseStylesCss(config)!;
    expect(result).toContain('Auto-generated by component2block');
  });

  it('body declarations are wrapped in body selector', () => {
    const result = generateBaseStylesCss(config)!;
    expect(result).toContain('body {');
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).toContain('font-family:');
  });

  it('body resolves token references to CSS variables', () => {
    const result = generateBaseStylesCss(config)!;
    expect(result).toContain('  font-family: var(--design-system--font-family-inter);');
    expect(result).toContain('  font-size: var(--design-system--font-size-medium);');
  });

  it('body passes raw values through unchanged', () => {
    const result = generateBaseStylesCss(config)!;
    expect(result).toContain('  font-weight: 400;');
    expect(result).toContain('  line-height: 1.6;');
  });

  it('does NOT emit layout utility rules', () => {
    // Block-gap, layout-constrained, has-global-padding all live in layout.css now.
    const result = generateBaseStylesCss(config)!;
    expect(result).not.toContain('is-layout-constrained');
    expect(result).not.toContain('has-global-padding');
    expect(result).not.toContain('is-layout-flex');
  });

  it('does NOT emit flow-spacing rules', () => {
    // Per-heading margins, after-heading, li + li all live in typography.css now.
    const result = generateBaseStylesCss(config)!;
    expect(result).not.toContain('* + h2');
    expect(result).not.toContain('h1, h2, h3, h4, h5, h6) + *');
    expect(result).not.toContain('li + li');
  });

  it('heading group uses :where(h1, h2, h3, h4, h5, h6) selector', () => {
    const result = generateBaseStylesCss(config)!;
    expect(result).toContain(':where(h1, h2, h3, h4, h5, h6) {');
  });

  it('individual headings use :where(hN) selectors', () => {
    const result = generateBaseStylesCss(config)!;
    expect(result).toContain(':where(h1) {');
    expect(result).toContain(':where(h2) {');
    expect(result).toContain(':where(h6) {');
  });

  it('h1.fontSize resolves to var() when referencing a defined token', () => {
    const cfg: C2bConfig = {
      ...config,
      tokens: {
        ...config.tokens,
        fontSize: {
          ...config.tokens.fontSize!,
          '2x-large': { value: '3rem', name: '2x Large', slug: '2x-large' },
        },
      },
      baseStyles: {
        ...config.baseStyles,
        h1: { fontSize: '2x-large', fontWeight: '500' },
      },
    };
    const result = generateBaseStylesCss(cfg)!;
    const h1Block = result.split(':where(h1) {')[1].split('}')[0];
    expect(h1Block).toContain('font-size: var(--design-system--font-size-2x-large);');
  });

  it('individual headings include font-style: normal by default', () => {
    const result = generateBaseStylesCss(config)!;
    const h1Block = result.split(':where(h1) {')[1].split('}')[0];
    expect(h1Block).toContain('font-style: normal;');
  });

  it('explicit fontStyle overrides the normal default', () => {
    const result = generateBaseStylesCss(config)!;
    const h6Block = result.split(':where(h6) {')[1].split('}')[0];
    expect(h6Block).toContain('font-style: italic;');
  });

  it('heading fontStyle default does not cross-resolve to a fontWeight token', () => {
    const cfg: C2bConfig = {
      ...config,
      tokens: {
        ...config.tokens,
        fontWeight: {
          normal: { value: '400' },
        },
      },
      baseStyles: {
        ...config.baseStyles,
        h1: { fontWeight: '500' },
      },
    };
    const result = generateBaseStylesCss(cfg)!;
    const h1Block = result.split(':where(h1) {')[1].split('}')[0];
    expect(h1Block).toContain('font-style: normal;');
    expect(h1Block).not.toMatch(/font-style: var\(--design-system--font-weight-normal\)/);
  });

  it('fontWeight token ref resolves to a font-weight CSS variable', () => {
    const cfg: C2bConfig = {
      ...config,
      baseStyles: {
        h1: { fontSize: 'medium', fontWeight: 'bold' },
      },
    };
    const result = generateBaseStylesCss(cfg)!;
    expect(result).toContain('  font-weight: var(--design-system--font-weight-bold);');
  });

  it('caption maps to :where(figcaption) selector', () => {
    const result = generateBaseStylesCss(config)!;
    expect(result).toContain(':where(figcaption) {');
  });

  it('caption resolves token references', () => {
    const result = generateBaseStylesCss(config)!;
    const captionBlock = result.split(':where(figcaption) {')[1].split('}')[0];
    expect(captionBlock).toContain('font-size: var(--design-system--font-size-small);');
  });

  it('outputs typography properties in canonical order', () => {
    const result = generateBaseStylesCss(config)!;
    const bodyBlock = result.split('body {')[1].split('}')[0];
    const ffIdx = bodyBlock.indexOf('font-family');
    const fsIdx = bodyBlock.indexOf('font-size');
    const fwIdx = bodyBlock.indexOf('font-weight');
    const lhIdx = bodyBlock.indexOf('line-height');
    expect(ffIdx).toBeLessThan(fsIdx);
    expect(fsIdx).toBeLessThan(fwIdx);
    expect(fwIdx).toBeLessThan(lhIdx);
  });
});

describe('generateBaseStylesCss — color and background', () => {
  const colorConfig: C2bConfig = {
    prefix: 'design-system',
    srcDir: 'src/styles',
    themeDir: 'dist/wp',
    bundleFonts: false,
    themeable: false,
    tokens: {
      colorPalette: {
        primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
        white: { value: '#ffffff', name: 'White', slug: 'white' },
      },
    },
    baseStyles: {
      body: { color: 'primary', background: 'white' },
      heading: { color: 'primary' },
      h2: { color: 'primary' },
      caption: { color: 'primary' },
    },
  };

  it('emits color declaration in body block', () => {
    const result = generateBaseStylesCss(colorConfig)!;
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).toContain('color: var(--design-system--color-primary);');
  });

  it('emits background-color declaration in body block', () => {
    const result = generateBaseStylesCss(colorConfig)!;
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).toContain('background-color: var(--design-system--color-white);');
  });

  it('emits heading color', () => {
    const result = generateBaseStylesCss(colorConfig)!;
    const headingBlock = result.split(':where(h1, h2, h3, h4, h5, h6) {')[1].split('}')[0];
    expect(headingBlock).toContain('color: var(--design-system--color-primary);');
  });

  it('emits individual heading color', () => {
    const result = generateBaseStylesCss(colorConfig)!;
    const h2Block = result.split(':where(h2) {')[1].split('}')[0];
    expect(h2Block).toContain('color: var(--design-system--color-primary);');
  });

  it('passes raw color values through', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { body: { color: '#ff0000', background: '#00ff00' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    expect(result).toContain('color: #ff0000;');
    expect(result).toContain('background-color: #00ff00;');
  });

  it('does not emit color declarations when not defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { body: { fontFamily: 'sans-serif' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).not.toContain('color:');
    expect(bodyBlock).not.toContain('background-color:');
  });
});

describe('generateBaseStylesCss — button and link', () => {
  const colorConfig: C2bConfig = {
    prefix: 'design-system',
    srcDir: 'src/styles',
    themeDir: 'dist/wp',
    bundleFonts: false,
    themeable: false,
    tokens: {
      colorPalette: {
        primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
        white: { value: '#ffffff', name: 'White', slug: 'white' },
        red: { value: '#ff0000', name: 'Red', slug: 'red' },
      },
    },
  };

  it('emits :where(button) selector with color and background', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { button: { color: 'white', background: 'primary' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    expect(result).toContain(':where(button) {');
    const buttonBlock = result.split(':where(button) {')[1].split('}')[0];
    expect(buttonBlock).toContain('color: var(--design-system--color-white);');
    expect(buttonBlock).toContain('background-color: var(--design-system--color-primary);');
  });

  it('emits button with only background', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { button: { background: 'primary' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    expect(result).toContain(':where(button) {');
    const buttonBlock = result.split(':where(button) {')[1].split('}')[0];
    // No standalone `color:` declaration — only the `background-color:` line should appear.
    expect(buttonBlock).not.toMatch(/^\s+color:/m);
    expect(buttonBlock).toContain('background-color: var(--design-system--color-primary);');
  });

  it('does not emit :where(button) when button not defined', () => {
    const cfg: C2bConfig = { ...colorConfig, baseStyles: {} };
    const result = generateBaseStylesCss(cfg);
    if (result) expect(result).not.toContain(':where(button)');
  });

  it('emits :where(a) selector with color', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { link: { color: 'primary' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    expect(result).toContain(':where(a) {');
    const linkBlock = result.split(':where(a) {')[1].split('}')[0];
    expect(linkBlock).toContain('color: var(--design-system--color-primary);');
  });

  it('emits :where(a:hover) selector when hoverColor is defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { link: { color: 'primary', hoverColor: 'red' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    expect(result).toContain(':where(a:hover) {');
    const hoverBlock = result.split(':where(a:hover) {')[1].split('}')[0];
    expect(hoverBlock).toContain('color: var(--design-system--color-red);');
  });

  it('does not emit :where(a:hover) when hoverColor is not defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { link: { color: 'primary' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    expect(result).toContain(':where(a) {');
    expect(result).not.toContain(':where(a:hover)');
  });

  it('passes raw hoverColor values through', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { link: { color: '#0000ff', hoverColor: '#ff0000' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    const linkBlock = result.split(':where(a) {')[1].split('}')[0];
    expect(linkBlock).toContain('color: #0000ff;');
    const hoverBlock = result.split(':where(a:hover) {')[1].split('}')[0];
    expect(hoverBlock).toContain('color: #ff0000;');
  });

  it('does not emit :where(a) when link not defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: { body: { color: 'primary' } },
    };
    const result = generateBaseStylesCss(cfg)!;
    expect(result).not.toContain(':where(a)');
  });
});
