import { describe, it, expect } from 'vitest';
import { generateContentScss } from '../src/generators/content-scss.js';
import type { C2bConfig } from '../src/types.js';

const config: C2bConfig = {
  prefix: 'design-system',
  tokensPath: 'src/styles/tokens.css',
  wpDir: 'dist/wp',
  wpThemeable: false,
  tokens: {
    fontFamily: {
      inter: { value: 'Inter, sans-serif', name: 'Inter', slug: 'inter' },
    },
    fontSize: {
      small: { value: '1rem', name: 'Small', slug: 'small' },
      medium: { value: '1.125rem', name: 'Medium', slug: 'medium' },
    },
  },
  baseStyles: {
    body: {
      fontFamily: 'inter',
      fontSize: 'medium',
      fontWeight: '400',
      lineHeight: '1.6',
    },
    heading: {
      fontFamily: 'inter',
    },
    h1: { fontSize: '4.5rem', fontWeight: '500' },
    h2: { fontSize: '3rem', fontWeight: '500' },
    h6: { fontSize: '1.45rem', fontWeight: '500', fontStyle: 'italic' },
    caption: { fontSize: 'small', fontStyle: 'italic', fontWeight: '300' },
  },
};

describe('generateContentScss', () => {
  it('returns null when no baseStyles', () => {
    const result = generateContentScss({ ...config, baseStyles: undefined });
    expect(result).toBeNull();
  });

  it('includes auto-generated header', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain('Auto-generated by component2block');
  });

  it('body declarations are wrapped in body selector', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain('body {');
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).toContain('font-family:');
  });

  it('body resolves token references to CSS variables', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain('  font-family: var(--design-system--font-family-inter);');
    expect(result).toContain('  font-size: var(--design-system--font-size-medium);');
  });

  it('body passes raw values through unchanged', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain('  font-weight: 400;');
    expect(result).toContain('  line-height: 1.6;');
  });

  it('heading group uses :where(h1, h2, h3, h4, h5, h6) selector', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain(':where(h1, h2, h3, h4, h5, h6) {');
    expect(result).toContain('  font-family: var(--design-system--font-family-inter);');
  });

  it('individual headings use :where(hN) selectors', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain(':where(h1) {');
    expect(result).toContain(':where(h2) {');
  });

  it('h1.fontSize resolves to var() when referencing a defined token', () => {
    // Regression: identifiers like "2x-large" start with a digit and used
    // to be classified as raw CSS, emitting a bare identifier. When the
    // token exists in tokens.fontSize, the generator must emit a var() ref.
    const cfg: C2bConfig = {
      ...config,
      tokens: {
        ...config.tokens,
        fontSize: {
          ...config.tokens.fontSize!,
          '2x-large': { value: '3rem', name: '2x Large', slug: '2x-large' },
        },
      },
      baseStyles: {
        ...config.baseStyles,
        h1: { fontSize: '2x-large', fontWeight: '500' },
      },
    };
    const result = generateContentScss(cfg)!;
    const h1Block = result.split(':where(h1) {')[1].split('}')[0];
    expect(h1Block).toContain('font-size: var(--design-system--font-size-2x-large);');
    expect(h1Block).not.toMatch(/font-size: 2x-large;/);
  });

  it('individual headings include font-style: normal by default', () => {
    const result = generateContentScss(config)!;
    // h1 has no fontStyle in config — should get normal
    const h1Block = result.split(':where(h1) {')[1].split('}')[0];
    expect(h1Block).toContain('font-style: normal;');
  });

  it('explicit fontStyle overrides the normal default', () => {
    const result = generateContentScss(config)!;
    // h6 has fontStyle: 'italic' in config
    const h6Block = result.split(':where(h6) {')[1].split('}')[0];
    expect(h6Block).toContain('font-style: italic;');
    expect(h6Block).not.toContain('font-style: normal;');
  });

  it('heading fontStyle default does not cross-resolve to a fontWeight token', () => {
    // Regression: ensureFontStyle() defaults headings to fontStyle: 'normal'.
    // Without strict per-property category resolution, "normal" would match
    // fontWeight.normal and incorrectly emit var(--prefix--font-weight-normal).
    const cfg: C2bConfig = {
      ...config,
      tokens: {
        ...config.tokens,
        fontWeight: {
          normal: { value: '400' },
          bold: { value: '700' },
        },
      },
    };
    const result = generateContentScss(cfg)!;
    const h1Block = result.split(':where(h1) {')[1].split('}')[0];
    expect(h1Block).toContain('font-style: normal;');
    expect(h1Block).not.toContain('font-style: var(--design-system--font-weight-normal)');
  });

  it('fontWeight token ref resolves to a font-weight CSS variable', () => {
    const cfg: C2bConfig = {
      ...config,
      tokens: {
        ...config.tokens,
        fontWeight: {
          normal: { value: '400' },
          medium: { value: '500' },
        },
      },
      baseStyles: {
        body: { fontWeight: 'normal' },
        h1: { fontSize: '4.5rem', fontWeight: 'medium' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain('font-weight: var(--design-system--font-weight-normal);');
    const h1Block = result.split(':where(h1) {')[1].split('}')[0];
    expect(h1Block).toContain('font-weight: var(--design-system--font-weight-medium);');
  });

  it('caption maps to :where(figcaption) selector', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain(':where(figcaption) {');
  });

  it('caption resolves token references', () => {
    const result = generateContentScss(config)!;
    const captionBlock = result.split(':where(figcaption) {')[1].split('}')[0];
    expect(captionBlock).toContain('font-size: var(--design-system--font-size-small);');
  });

  it('outputs properties in consistent order', () => {
    const result = generateContentScss(config)!;
    // In body: fontFamily before fontSize before fontWeight before lineHeight
    const fontFamilyIdx = result.indexOf('  font-family: var(--design-system--font-family-inter);');
    const fontSizeIdx = result.indexOf('  font-size: var(--design-system--font-size-medium);');
    const fontWeightIdx = result.indexOf('  font-weight: 400;');
    const lineHeightIdx = result.indexOf('  line-height: 1.6;');
    expect(fontFamilyIdx).toBeLessThan(fontSizeIdx);
    expect(fontSizeIdx).toBeLessThan(fontWeightIdx);
    expect(fontWeightIdx).toBeLessThan(lineHeightIdx);
  });
});

describe('generateContentScss — spacing padding', () => {
  const spacingConfig: C2bConfig = {
    prefix: 'design-system',
    tokensPath: 'src/styles/tokens.css',
    wpDir: 'dist/wp',
    wpThemeable: false,
    tokens: {
      spacing: {
        large: { value: 'min(2.25rem, 3vw)', slug: '60', name: 'Large' },
      },
      fontFamily: {
        inter: { value: 'Inter, sans-serif', name: 'Inter', slug: 'inter' },
      },
    },
    baseStyles: {
      body: { fontFamily: 'inter', fontWeight: '400' },
      spacing: {
        padding: {
          top: '0',
          right: 'large',
          bottom: '0',
          left: 'large',
        },
      },
    },
  };

  it('generates root padding CSS variables in body block', () => {
    const result = generateContentScss(spacingConfig)!;
    expect(result).toContain('  --design-system--root-padding-top: 0;');
    expect(result).toContain('  --design-system--root-padding-right: var(--design-system--spacing-large);');
    expect(result).toContain('  --design-system--root-padding-bottom: 0;');
    expect(result).toContain('  --design-system--root-padding-left: var(--design-system--spacing-large);');
  });

  it('generates .has-global-padding class with horizontal padding', () => {
    const result = generateContentScss(spacingConfig)!;
    expect(result).toContain('.has-global-padding {');
    expect(result).toContain('  padding-right: var(--design-system--root-padding-right);');
    expect(result).toContain('  padding-left: var(--design-system--root-padding-left);');
  });

  it('generates .alignfull breakout rules', () => {
    const result = generateContentScss(spacingConfig)!;
    expect(result).toContain('.has-global-padding > .alignfull {');
    expect(result).toContain('  max-width: none;');
    expect(result).toContain('  margin-right: calc(var(--design-system--root-padding-right) * -1);');
    expect(result).toContain('  margin-left: calc(var(--design-system--root-padding-left) * -1);');
  });

  it('generates nested .has-global-padding restore rule', () => {
    const result = generateContentScss(spacingConfig)!;
    expect(result).toContain('.has-global-padding > .alignfull > .has-global-padding {');
    expect(result).toContain('  padding-right: var(--design-system--root-padding-right);');
    expect(result).toContain('  padding-left: var(--design-system--root-padding-left);');
  });

  it('resolves token references in padding values', () => {
    const result = generateContentScss(spacingConfig)!;
    expect(result).toContain('var(--design-system--spacing-large)');
  });

  it('passes raw padding values through unchanged', () => {
    const result = generateContentScss(spacingConfig)!;
    expect(result).toContain('--design-system--root-padding-top: 0;');
    expect(result).toContain('--design-system--root-padding-bottom: 0;');
  });

  it('creates body block with just padding vars when no body typography', () => {
    const spacingOnlyConfig: C2bConfig = {
      ...spacingConfig,
      baseStyles: {
        spacing: {
          padding: { right: 'large', left: 'large' },
        },
      },
    };
    const result = generateContentScss(spacingOnlyConfig)!;
    expect(result).toContain('body {');
    expect(result).toContain('--design-system--root-padding-right: var(--design-system--spacing-large);');
    expect(result).not.toContain('font-family:');
  });

  it('produces no padding or alignfull rules when no spacing config', () => {
    const noSpacingConfig: C2bConfig = {
      ...spacingConfig,
      baseStyles: {
        body: { fontFamily: 'inter' },
      },
    };
    const result = generateContentScss(noSpacingConfig)!;
    expect(result).not.toContain('root-padding');
    expect(result).not.toContain('.has-global-padding');
    expect(result).not.toContain('.alignfull');
  });

  it('only outputs defined padding sides', () => {
    const partialConfig: C2bConfig = {
      ...spacingConfig,
      baseStyles: {
        spacing: {
          padding: { right: 'large', left: 'large' },
        },
      },
    };
    const result = generateContentScss(partialConfig)!;
    expect(result).toContain('--design-system--root-padding-right:');
    expect(result).toContain('--design-system--root-padding-left:');
    expect(result).not.toContain('--design-system--root-padding-top:');
    expect(result).not.toContain('--design-system--root-padding-bottom:');
  });
});

describe('generateContentScss — spacing blockGap', () => {
  const blockGapConfig: C2bConfig = {
    prefix: 'design-system',
    tokensPath: 'src/styles/tokens.css',
    wpDir: 'dist/wp',
    wpThemeable: false,
    tokens: {
      spacing: {
        medium: { value: 'min(1.5rem, 2vw)', slug: '50', name: 'Medium' },
        large: { value: 'min(2.25rem, 3vw)', slug: '60', name: 'Large' },
      },
    },
    baseStyles: {
      spacing: {
        blockGap: 'medium',
      },
    },
  };

  it('generates root block gap CSS variable in body block', () => {
    const result = generateContentScss(blockGapConfig)!;
    expect(result).toContain('  --design-system--root-block-gap: var(--design-system--spacing-medium);');
  });

  it('generates constrained layout rule', () => {
    const result = generateContentScss(blockGapConfig)!;
    expect(result).toContain(':where(.is-layout-constrained) > * + * {');
    expect(result).toContain('  margin-block-start: var(--design-system--root-block-gap);');
  });

  it('generates flex layout rule', () => {
    const result = generateContentScss(blockGapConfig)!;
    expect(result).toContain(':where(.is-layout-flex) {');
    expect(result).toContain('  gap: var(--design-system--root-block-gap);');
  });

  it('generates grid layout rule', () => {
    const result = generateContentScss(blockGapConfig)!;
    expect(result).toContain(':where(.is-layout-grid) {');
    expect(result).toContain('  gap: var(--design-system--root-block-gap);');
  });

  it('resolves token references in blockGap value', () => {
    const result = generateContentScss(blockGapConfig)!;
    expect(result).toContain('var(--design-system--spacing-medium)');
  });

  it('passes raw blockGap values through unchanged', () => {
    const rawConfig: C2bConfig = {
      ...blockGapConfig,
      baseStyles: {
        spacing: { blockGap: '2rem' },
      },
    };
    const result = generateContentScss(rawConfig)!;
    expect(result).toContain('--design-system--root-block-gap: 2rem;');
  });

  it('does not produce block gap rules when blockGap absent', () => {
    const noGapConfig: C2bConfig = {
      ...blockGapConfig,
      baseStyles: {
        spacing: {
          padding: { right: 'large', left: 'large' },
        },
      },
    };
    const result = generateContentScss(noGapConfig)!;
    expect(result).not.toContain('root-block-gap');
    expect(result).not.toContain('.is-layout-constrained');
    expect(result).not.toContain('.is-layout-flex');
    expect(result).not.toContain('.is-layout-grid');
  });

  it('generates both blockGap and padding when both defined', () => {
    const bothConfig: C2bConfig = {
      ...blockGapConfig,
      baseStyles: {
        spacing: {
          blockGap: 'medium',
          padding: { right: 'large', left: 'large' },
        },
      },
    };
    const result = generateContentScss(bothConfig)!;
    expect(result).toContain('--design-system--root-block-gap:');
    expect(result).toContain('--design-system--root-padding-right:');
    expect(result).toContain('.is-layout-constrained');
    expect(result).toContain('.has-global-padding');
  });

  it('creates body block with just blockGap when no typography or padding', () => {
    const result = generateContentScss(blockGapConfig)!;
    expect(result).toContain('body {');
    expect(result).toContain('--design-system--root-block-gap:');
    expect(result).not.toContain('font-family:');
    expect(result).not.toContain('root-padding');
  });
});

describe('generateContentScss — layout constraints', () => {
  const layoutConfig: C2bConfig = {
    prefix: 'design-system',
    tokensPath: 'src/styles/tokens.css',
    wpDir: 'dist/wp',
    wpThemeable: false,
    tokens: {
      layout: {
        contentSize: { value: '768px' },
        wideSize: { value: '1280px' },
      },
    },
    baseStyles: {
      body: { fontWeight: '400' },
    },
  };

  it('generates default content-size constraint rule', () => {
    const result = generateContentScss(layoutConfig)!;
    expect(result).toContain('.is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {');
    expect(result).toContain('  max-width: var(--design-system--layout-content-size);');
  });

  it('generates alignwide rule with wide-size', () => {
    const result = generateContentScss(layoutConfig)!;
    expect(result).toContain('.is-layout-constrained > .alignwide {');
    expect(result).toContain('  max-width: var(--design-system--layout-wide-size);');
  });

  it('includes !important on auto margins for both rules', () => {
    const result = generateContentScss(layoutConfig)!;
    const contentBlock = result.split('.is-layout-constrained > :where(:not')[1].split('}')[0];
    expect(contentBlock).toContain('margin-left: auto !important;');
    expect(contentBlock).toContain('margin-right: auto !important;');
    const wideBlock = result.split('.is-layout-constrained > .alignwide {')[1].split('}')[0];
    expect(wideBlock).toContain('margin-left: auto !important;');
    expect(wideBlock).toContain('margin-right: auto !important;');
  });

  it('generates only content-size rule when wide-size absent', () => {
    const contentOnlyConfig: C2bConfig = {
      ...layoutConfig,
      tokens: {
        layout: { contentSize: { value: '768px' } },
      },
    };
    const result = generateContentScss(contentOnlyConfig)!;
    expect(result).toContain('var(--design-system--layout-content-size)');
    expect(result).not.toContain('.alignwide');
  });

  it('generates only alignwide rule when content-size absent', () => {
    const wideOnlyConfig: C2bConfig = {
      ...layoutConfig,
      tokens: {
        layout: { wideSize: { value: '1280px' } },
      },
    };
    const result = generateContentScss(wideOnlyConfig)!;
    expect(result).toContain('.is-layout-constrained > .alignwide {');
    expect(result).not.toContain(':where(:not(.alignleft)');
  });

  it('does not generate constraint rules when no layout tokens defined', () => {
    const noLayoutConfig: C2bConfig = {
      ...layoutConfig,
      tokens: {},
    };
    const result = generateContentScss(noLayoutConfig)!;
    expect(result).not.toContain('.is-layout-constrained > :where');
    expect(result).not.toContain('.alignwide');
  });

  it('does not generate constraint rules when layout tokens exist but no baseStyles', () => {
    const noBaseStylesConfig: C2bConfig = {
      ...layoutConfig,
      baseStyles: undefined,
    };
    const result = generateContentScss(noBaseStylesConfig);
    expect(result).toBeNull();
  });

  it('works alongside block gap and padding rules', () => {
    const fullConfig: C2bConfig = {
      ...layoutConfig,
      tokens: {
        layout: {
          contentSize: { value: '768px' },
          wideSize: { value: '1280px' },
        },
        spacing: {
          medium: { value: '1rem', slug: '50', name: 'Medium' },
          large: { value: '1.5rem', slug: '60', name: 'Large' },
        },
      },
      baseStyles: {
        body: { fontWeight: '400' },
        spacing: {
          blockGap: 'medium',
          padding: { right: 'large', left: 'large' },
        },
      },
    };
    const result = generateContentScss(fullConfig)!;
    expect(result).toContain(':where(.is-layout-constrained) > * + * {');
    expect(result).toContain('.is-layout-constrained > :where(:not(.alignleft)');
    expect(result).toContain('.is-layout-constrained > .alignwide {');
    expect(result).toContain('.has-global-padding {');
    expect(result).toContain('.has-global-padding > .alignfull {');
  });
});

describe('generateContentScss — baseStyles color', () => {
  const colorConfig: C2bConfig = {
    prefix: 'design-system',
    tokensPath: 'src/styles/tokens.css',
    wpDir: 'dist/wp',
    wpThemeable: false,
    tokens: {
      colorPalette: {
        primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
        secondary: { value: '#23282d', name: 'Secondary', slug: 'secondary' },
        base: { value: '#ffffff', name: 'Base', slug: 'base' },
      },
      fontFamily: {
        inter: { value: 'Inter, sans-serif', name: 'Inter', slug: 'inter' },
      },
    },
  };

  it('emits color declaration in body block', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        body: { color: 'secondary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain('color: var(--design-system--color-secondary);');
  });

  it('emits background-color declaration in body block', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        body: { background: 'base' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain('background-color: var(--design-system--color-base);');
  });

  it('emits both color and background-color alongside typography', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        body: { fontFamily: 'inter', color: 'secondary', background: 'base' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain('font-family: var(--design-system--font-family-inter);');
    expect(result).toContain('color: var(--design-system--color-secondary);');
    expect(result).toContain('background-color: var(--design-system--color-base);');
  });

  it('emits heading color', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        heading: { color: 'primary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain(':where(h1, h2, h3, h4, h5, h6) {');
    expect(result).toContain('color: var(--design-system--color-primary);');
  });

  it('emits individual heading color', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        h1: { fontSize: '4.5rem', color: 'primary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain(':where(h1) {');
    expect(result).toContain('color: var(--design-system--color-primary);');
  });

  it('passes raw color values through', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        body: { color: '#333333', background: '#ffffff' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain('color: #333333;');
    expect(result).toContain('background-color: #ffffff;');
  });

  it('does not emit color declarations when not defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        body: { fontFamily: 'inter' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).not.toMatch(/^\s+color:/m);
    expect(result).not.toContain('background-color:');
  });

  it('emits caption color', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        caption: { color: 'secondary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain(':where(figcaption) {');
    expect(result).toContain('color: var(--design-system--color-secondary);');
  });
});

describe('generateContentScss — button element', () => {
  const colorConfig: C2bConfig = {
    prefix: 'design-system',
    tokensPath: 'src/styles/tokens.css',
    wpDir: 'dist/wp',
    wpThemeable: false,
    tokens: {
      colorPalette: {
        primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
        'off-white': { value: '#f8f8f8', name: 'Off White', slug: 'off-white' },
      },
    },
  };

  it('emits :where(button) selector with color and background', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        button: { color: 'off-white', background: 'primary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain(':where(button) {');
    expect(result).toContain('color: var(--design-system--color-off-white);');
    expect(result).toContain('background-color: var(--design-system--color-primary);');
  });

  it('emits button with only background', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        button: { background: 'primary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain(':where(button) {');
    expect(result).toContain('background-color: var(--design-system--color-primary);');
  });

  it('does not emit :where(button) when button not defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        body: { color: 'primary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).not.toContain(':where(button)');
  });
});

describe('generateContentScss — link element', () => {
  const colorConfig: C2bConfig = {
    prefix: 'design-system',
    tokensPath: 'src/styles/tokens.css',
    wpDir: 'dist/wp',
    wpThemeable: false,
    tokens: {
      colorPalette: {
        primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
        warning: { value: '#dba617', name: 'Warning', slug: 'warning' },
      },
    },
  };

  it('emits :where(a) selector with color', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        link: { color: 'primary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain(':where(a) {');
    expect(result).toContain('color: var(--design-system--color-primary);');
  });

  it('emits :where(a:hover) selector when hoverColor is defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        link: { color: 'primary', hoverColor: 'warning' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain(':where(a) {');
    expect(result).toContain(':where(a:hover) {');
    const hoverBlock = result.split(':where(a:hover) {')[1].split('}')[0];
    expect(hoverBlock).toContain('color: var(--design-system--color-warning);');
  });

  it('does not emit :where(a:hover) when hoverColor is not defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        link: { color: 'primary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).toContain(':where(a) {');
    expect(result).not.toContain(':where(a:hover)');
  });

  it('passes raw hoverColor values through', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        link: { color: '#0000ff', hoverColor: '#ff0000' },
      },
    };
    const result = generateContentScss(cfg)!;
    const linkBlock = result.split(':where(a) {')[1].split('}')[0];
    expect(linkBlock).toContain('color: #0000ff;');
    const hoverBlock = result.split(':where(a:hover) {')[1].split('}')[0];
    expect(hoverBlock).toContain('color: #ff0000;');
  });

  it('does not emit :where(a) when link not defined', () => {
    const cfg: C2bConfig = {
      ...colorConfig,
      baseStyles: {
        body: { color: 'primary' },
      },
    };
    const result = generateContentScss(cfg)!;
    expect(result).not.toContain(':where(a)');
  });
});
