import { describe, it, expect } from 'vitest';
import { generateLayoutCss } from '../src/generators/layout-css.js';
import type { C2bConfig } from '../src/types.js';

const layoutConfig: C2bConfig = {
  prefix: 'design-system',
  srcDir: 'src/styles',
  themeDir: 'dist/wp',
  bundleFonts: false,
  themeable: false,
  tokens: {
    spacing: {
      small: { value: '0.5rem', slug: '20', name: 'Small' },
      medium: { value: '1rem', slug: '40', name: 'Medium' },
      large: { value: '2rem', slug: '60', name: 'Large' },
    },
    layout: {
      contentSize: { value: '768px' },
      wideSize: { value: '1200px' },
    },
  },
  baseStyles: {
    spacing: {
      blockGap: 'medium',
      padding: { top: '0', right: 'large', bottom: '0', left: 'large' },
    },
  },
};

describe('generateLayoutCss', () => {
  it('returns null when no layout/spacing/blockGap configured and no layout tokens', () => {
    const result = generateLayoutCss({
      ...layoutConfig,
      tokens: {},
      baseStyles: undefined,
    });
    expect(result).toBeNull();
  });

  it('includes auto-generated header', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('Auto-generated by component2block');
  });

  it('does not declare the root spacing vars (they are tokens in tokens.css)', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).not.toContain('body {');
    expect(result).not.toMatch(/^\s*--design-system--root-[\w-]+:/m);
  });

  it('follows the header with a single blank line', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result.startsWith('/* Auto-generated by component2block — do not edit manually */\n\n:')).toBe(true);
  });

  it('emits the constrained block-gap rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain(':where(.is-layout-constrained) > * + * {');
    expect(result).toContain('  margin-block-start: var(--design-system--root-block-gap);');
  });

  it('emits the > * reset (kills browser default vertical margins; first-child gets 0)', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toMatch(/:where\(\.is-layout-constrained\) > \* \{[^}]*margin-block-start: 0;[^}]*margin-block-end: 0;/);
  });

  it('reset rule comes before the > * + * block-gap rule (source order matters)', () => {
    const result = generateLayoutCss(layoutConfig)!;
    const resetIdx = result.indexOf(':where(.is-layout-constrained) > * {');
    const gapIdx = result.indexOf(':where(.is-layout-constrained) > * + * {');
    expect(resetIdx).toBeGreaterThan(-1);
    expect(gapIdx).toBeGreaterThan(resetIdx);
  });

  it('emits flex/grid gap rules', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain(':where(.is-layout-flex) {');
    expect(result).toContain(':where(.is-layout-grid) {');
    expect(result).toContain('  gap: var(--design-system--root-block-gap);');
  });

  it('does not emit block-gap rules when blockGap absent', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { padding: { top: '0' } } },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).not.toContain(':where(.is-layout-constrained) > * + *');
    expect(result).not.toContain(':where(.is-layout-flex)');
  });

  it('emits content-size constraint rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain(
      '.is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {',
    );
    expect(result).toContain('  max-width: var(--design-system--layout-content-size);');
  });

  it('emits alignwide constraint rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('.is-layout-constrained > .alignwide {');
    expect(result).toContain('  max-width: var(--design-system--layout-wide-size);');
  });

  it('includes !important on auto margins for both constraint rules', () => {
    const result = generateLayoutCss(layoutConfig)!;
    const matches = result.match(/margin-(left|right): auto !important;/g);
    expect(matches?.length).toBeGreaterThanOrEqual(4);
  });

  it('emits .has-global-padding rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('.has-global-padding {');
    const block = result.split('.has-global-padding {')[1].split('}')[0];
    expect(block).toContain('  padding-right: var(--design-system--root-padding-right);');
    expect(block).toContain('  padding-left: var(--design-system--root-padding-left);');
  });

  it('emits .alignfull breakout rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('.has-global-padding > .alignfull {');
    expect(result).toContain('  max-width: none;');
    expect(result).toContain(
      '  margin-right: calc(var(--design-system--root-padding-right) * -1);',
    );
  });

  it('emits nested .has-global-padding restore rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('.has-global-padding > .alignfull > .has-global-padding {');
  });

  it('does not emit padding-related rules when no padding configured', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { blockGap: 'medium' } },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).not.toContain('.has-global-padding');
    // The layout-constraint rule legitimately mentions `:not(.alignfull)`, so
    // assert specifically against the padding-related .alignfull breakout rule.
    expect(result).not.toContain('.has-global-padding > .alignfull');
  });

  it('does not emit constraint rules when no layout tokens defined', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      tokens: { spacing: layoutConfig.tokens.spacing! },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).not.toContain('is-layout-constrained > .alignwide');
    expect(result).not.toContain('is-layout-constrained > :where(:not');
  });

  it('emits only content-size rule when wideSize absent', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      tokens: {
        ...layoutConfig.tokens,
        layout: { contentSize: layoutConfig.tokens.layout!.contentSize },
      },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).toContain(':not(.alignleft):not(.alignright):not(.alignfull)');
    expect(result).not.toContain('.is-layout-constrained > .alignwide');
  });

  it('emits .has-global-padding rules when only the x axis is set', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { padding: { x: 'large' } } },
    };
    const block = generateLayoutCss(cfg)!.split('.has-global-padding {')[1].split('}')[0];
    expect(block).toContain('  padding-right: var(--design-system--root-padding-right);');
    expect(block).toContain('  padding-left: var(--design-system--root-padding-left);');
  });

  it('omits .has-global-padding rules when only vertical padding is set', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { padding: { y: 'medium' } } },
    };
    expect(generateLayoutCss(cfg)!).not.toContain('.has-global-padding');
    // With nothing else layout-relevant configured, there is no file at all.
    expect(generateLayoutCss({ ...cfg, tokens: { spacing: layoutConfig.tokens.spacing! } })).toBeNull();
  });

  it('emits when only layout tokens are defined (no baseStyles)', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: undefined,
    };
    const result = generateLayoutCss(cfg)!;
    // Constraint rules from layout tokens still emit
    expect(result).toContain('.is-layout-constrained > .alignwide');
    // But no body block
    expect(result).not.toContain('body {');
  });

  it('emits the entry-content sibling rule with a resolved spacing token', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: {
        spacing: { blockGap: 'medium', entryContent: 'large' },
      },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).toContain(':where(.entry-content) > * + * {');
    expect(result).toContain('  margin-block-start: var(--design-system--spacing-large);');
  });

  it('passes raw entryContent values through unchanged', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { entryContent: '1.5rem' } },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).toContain(':where(.entry-content) > * + * {');
    expect(result).toContain('  margin-block-start: 1.5rem;');
  });

  it('does not emit entry-content rule when not configured', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).not.toContain('.entry-content');
  });

  it('entry-content rule comes after block-gap rules and before layout-constraint rules', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: {
        spacing: { blockGap: 'medium', entryContent: 'large' },
      },
    };
    const result = generateLayoutCss(cfg)!;
    const blockGapIdx = result.indexOf(':where(.is-layout-grid)');
    const entryIdx = result.indexOf(':where(.entry-content)');
    const constraintIdx = result.indexOf('.is-layout-constrained > .alignwide');
    expect(blockGapIdx).toBeGreaterThan(-1);
    expect(entryIdx).toBeGreaterThan(blockGapIdx);
    expect(constraintIdx).toBeGreaterThan(entryIdx);
  });

  it('emits layout.css when only entryContent is configured', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      tokens: { spacing: layoutConfig.tokens.spacing! },
      baseStyles: { spacing: { entryContent: 'large' } },
    };
    const result = generateLayoutCss(cfg);
    expect(result).not.toBeNull();
    expect(result!).toContain(':where(.entry-content) > * + *');
  });
});
