import { describe, it, expect } from 'vitest';
import { generateLayoutCss } from '../src/generators/layout-css.js';
import type { C2bConfig } from '../src/types.js';

const layoutConfig: C2bConfig = {
  prefix: 'design-system',
  srcDir: 'src/styles',
  themeDir: 'dist/wp',
  bundleFonts: false,
  themeable: false,
  tokens: {
    spacing: {
      small: { value: '0.5rem', slug: '20', name: 'Small' },
      medium: { value: '1rem', slug: '40', name: 'Medium' },
      large: { value: '2rem', slug: '60', name: 'Large' },
    },
    layout: {
      contentSize: { value: '768px' },
      wideSize: { value: '1200px' },
    },
  },
  baseStyles: {
    spacing: {
      blockGap: 'medium',
      padding: { top: '0', right: 'large', bottom: '0', left: 'large' },
    },
  },
};

describe('generateLayoutCss', () => {
  it('returns null when no layout/spacing/blockGap configured and no layout tokens', () => {
    const result = generateLayoutCss({
      ...layoutConfig,
      tokens: {},
      baseStyles: undefined,
    });
    expect(result).toBeNull();
  });

  it('includes auto-generated header', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('Auto-generated by component2block');
  });

  it('emits root padding CSS variables in body block', () => {
    const result = generateLayoutCss(layoutConfig)!;
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).toContain('--design-system--root-padding-top: 0;');
    expect(bodyBlock).toContain('--design-system--root-padding-right: var(--design-system--spacing-large);');
    expect(bodyBlock).toContain('--design-system--root-padding-bottom: 0;');
    expect(bodyBlock).toContain('--design-system--root-padding-left: var(--design-system--spacing-large);');
  });

  it('emits root block-gap CSS variable in body block', () => {
    const result = generateLayoutCss(layoutConfig)!;
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).toContain('--design-system--root-block-gap: var(--design-system--spacing-medium);');
  });

  it('does NOT emit body typography (lives in base-styles.css)', () => {
    const result = generateLayoutCss(layoutConfig)!;
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).not.toContain('font-family:');
    expect(bodyBlock).not.toContain('font-size:');
  });

  it('emits the constrained block-gap rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain(':where(.is-layout-constrained) > * + * {');
    expect(result).toContain('  margin-block-start: var(--design-system--root-block-gap);');
  });

  it('emits the > * reset (kills browser default vertical margins; first-child gets 0)', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toMatch(/:where\(\.is-layout-constrained\) > \* \{[^}]*margin-block-start: 0;[^}]*margin-block-end: 0;/);
  });

  it('reset rule comes before the > * + * block-gap rule (source order matters)', () => {
    const result = generateLayoutCss(layoutConfig)!;
    const resetIdx = result.indexOf(':where(.is-layout-constrained) > * {');
    const gapIdx = result.indexOf(':where(.is-layout-constrained) > * + * {');
    expect(resetIdx).toBeGreaterThan(-1);
    expect(gapIdx).toBeGreaterThan(resetIdx);
  });

  it('emits flex/grid gap rules', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain(':where(.is-layout-flex) {');
    expect(result).toContain(':where(.is-layout-grid) {');
    expect(result).toContain('  gap: var(--design-system--root-block-gap);');
  });

  it('does not emit block-gap rules when blockGap absent', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { padding: { top: '0' } } },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).not.toContain(':where(.is-layout-constrained) > * + *');
    expect(result).not.toContain(':where(.is-layout-flex)');
  });

  it('emits content-size constraint rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain(
      '.is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {',
    );
    expect(result).toContain('  max-width: var(--design-system--layout-content-size);');
  });

  it('emits alignwide constraint rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('.is-layout-constrained > .alignwide {');
    expect(result).toContain('  max-width: var(--design-system--layout-wide-size);');
  });

  it('includes !important on auto margins for both constraint rules', () => {
    const result = generateLayoutCss(layoutConfig)!;
    const matches = result.match(/margin-(left|right): auto !important;/g);
    expect(matches?.length).toBeGreaterThanOrEqual(4);
  });

  it('emits .has-global-padding rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('.has-global-padding {');
    const block = result.split('.has-global-padding {')[1].split('}')[0];
    expect(block).toContain('  padding-right: var(--design-system--root-padding-right);');
    expect(block).toContain('  padding-left: var(--design-system--root-padding-left);');
  });

  it('emits .alignfull breakout rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('.has-global-padding > .alignfull {');
    expect(result).toContain('  max-width: none;');
    expect(result).toContain(
      '  margin-right: calc(var(--design-system--root-padding-right) * -1);',
    );
  });

  it('emits nested .has-global-padding restore rule', () => {
    const result = generateLayoutCss(layoutConfig)!;
    expect(result).toContain('.has-global-padding > .alignfull > .has-global-padding {');
  });

  it('does not emit padding-related rules when no padding configured', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { blockGap: 'medium' } },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).not.toContain('.has-global-padding');
    // The layout-constraint rule legitimately mentions `:not(.alignfull)`, so
    // assert specifically against the padding-related .alignfull breakout rule.
    expect(result).not.toContain('.has-global-padding > .alignfull');
  });

  it('does not emit constraint rules when no layout tokens defined', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      tokens: { spacing: layoutConfig.tokens.spacing! },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).not.toContain('is-layout-constrained > .alignwide');
    expect(result).not.toContain('is-layout-constrained > :where(:not');
  });

  it('emits only content-size rule when wideSize absent', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      tokens: {
        ...layoutConfig.tokens,
        layout: { contentSize: layoutConfig.tokens.layout!.contentSize },
      },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).toContain(':not(.alignleft):not(.alignright):not(.alignfull)');
    expect(result).not.toContain('.is-layout-constrained > .alignwide');
  });

  it('only outputs defined padding sides', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { padding: { top: 'medium' } } },
    };
    const result = generateLayoutCss(cfg)!;
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).toContain('--design-system--root-padding-top:');
    expect(bodyBlock).not.toContain('--design-system--root-padding-right');
    expect(bodyBlock).not.toContain('--design-system--root-padding-left');
  });

  it('passes raw padding values through unchanged', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: { spacing: { padding: { top: '12px', right: '1rem' } } },
    };
    const result = generateLayoutCss(cfg)!;
    expect(result).toContain('--design-system--root-padding-top: 12px;');
    expect(result).toContain('--design-system--root-padding-right: 1rem;');
  });

  it('emits when only layout tokens are defined (no baseStyles)', () => {
    const cfg: C2bConfig = {
      ...layoutConfig,
      baseStyles: undefined,
    };
    const result = generateLayoutCss(cfg)!;
    // Constraint rules from layout tokens still emit
    expect(result).toContain('.is-layout-constrained > .alignwide');
    // But no body block
    expect(result).not.toContain('body {');
  });
});
