import { describe, it, expect } from 'vitest';
import { generateTokensScss } from '../src/generators/tokens-scss.js';
import type { C2bConfig } from '../src/types.js';

describe('generateTokensScss — opt-in via scssVars', () => {
  const baseConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    themeDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorPalette: {
        primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
      },
      spacing: {
        md: { value: '1rem', slug: '40', name: 'Medium' },
      },
      viewport: {
        mobile: { value: '500px' },
        tablet: { value: '800px' },
      },
    },
  };

  it('returns null when scssVars is empty or unset', () => {
    expect(generateTokensScss(baseConfig)).toBeNull();
    expect(generateTokensScss({ ...baseConfig, scssVars: [] })).toBeNull();
  });

  it('emits only selected categories', () => {
    const output = generateTokensScss({ ...baseConfig, scssVars: ['viewport'] });
    expect(output).not.toBeNull();
    expect(output).toContain('// Viewport');
    expect(output).toContain('$test-viewport-mobile: 500px;');
    expect(output).toContain('$test-viewport-tablet: 800px;');
    expect(output).not.toContain('// Colors');
    expect(output).not.toContain('// Spacing');
    expect(output).not.toContain('color-primary');
  });

  it('supports multiple categories in registry order (not config order)', () => {
    const output = generateTokensScss({
      ...baseConfig,
      // Ask for viewport first, but expect colorPalette first in output
      // because CATEGORY_ORDER puts colors ahead of viewport.
      scssVars: ['viewport', 'colorPalette', 'spacing'],
    })!;
    const colorIdx = output.indexOf('// Colors');
    const spacingIdx = output.indexOf('// Spacing');
    const viewportIdx = output.indexOf('// Viewport');
    expect(colorIdx).toBeGreaterThan(0);
    expect(spacingIdx).toBeGreaterThan(colorIdx);
    expect(viewportIdx).toBeGreaterThan(spacingIdx);
  });

  it('includes the auto-generated header', () => {
    const output = generateTokensScss({ ...baseConfig, scssVars: ['viewport'] })!;
    expect(output).toContain('// Auto-generated by component2block');
  });

  it('does not wrap variable declarations in :root or any selector', () => {
    // colorPalette rather than viewport: viewport also emits @mixin blocks,
    // which legitimately contain braces. This asserts the plain variable output.
    const output = generateTokensScss({ ...baseConfig, scssVars: ['colorPalette'] })!;
    expect(output).not.toContain(':root');
    expect(output).not.toContain('{');
    expect(output).not.toContain('}');
  });

  it('emits viewport variables before the mixins that reference them', () => {
    const output = generateTokensScss({ ...baseConfig, scssVars: ['viewport'] })!;
    expect(output.indexOf('$test-viewport-mobile:')).toBeLessThan(output.indexOf('@mixin'));
    expect(output).not.toContain(':root');
  });

  it('uses single-dash separators, not CSS custom property --', () => {
    const output = generateTokensScss({ ...baseConfig, scssVars: ['colorPalette'] })!;
    expect(output).not.toContain('--');
  });

  it('skips selected categories that have no tokens defined', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['viewport', 'spacing'],
      tokens: {
        viewport: {
          mobile: { value: '500px' },
        },
      },
    })!;
    expect(output).toContain('$test-viewport-mobile: 500px;');
    expect(output).not.toContain('// Spacing');
  });
});

describe('generateTokensScss — category-specific formatting', () => {
  it('includes cssOnly tokens for opted-in categories', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['colorPalette'],
      tokens: {
        colorPalette: {
          primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
          'primary-hover': { value: '#005a87', cssOnly: true },
        },
      },
    })!;
    expect(output).toContain('$test-color-primary: #0073aa;');
    expect(output).toContain('$test-color-primary-hover: #005a87;');
  });

  it('applies camelToKebab conversion for layout keys', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['layout'],
      tokens: {
        layout: {
          contentSize: { value: '645px' },
          wideSize: { value: '1340px' },
        },
      },
    })!;
    expect(output).toContain('$test-layout-content-size: 645px;');
    expect(output).toContain('$test-layout-wide-size: 1340px;');
  });

  it('emits viewport tokens when opted into scssVars', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['viewport'],
      tokens: {
        viewport: {
          mobile: { value: '500px' },
          tablet: { value: '800px' },
        },
      },
    })!;
    expect(output).toContain('$test-viewport-mobile: 500px;');
    expect(output).toContain('$test-viewport-tablet: 800px;');
  });

  it('emits fluid clamp() identical to tokens.css', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['fontSize'],
      tokens: {
        fontSize: {
          medium: {
            value: '1.125rem',
            slug: 'medium',
            name: 'Medium',
            fluid: { min: '0.875rem', max: '1.125rem' },
          },
          static: { value: '0.75rem', slug: 'static', name: 'Static' },
        },
      },
    })!;
    expect(output).toContain(
      '$test-font-size-medium: clamp(0.875rem, 0.875rem + ((1vw - 0.2rem) * 0.313), 1.125rem);',
    );
    expect(output).toContain('$test-font-size-static: 0.75rem;');
  });
});

describe('generateTokensScss — snapshot', () => {
  it('matches the expected file shape for a spacing + viewport config', () => {
    const snapshotConfig: C2bConfig = {
      prefix: 'rds',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['spacing', 'viewport'],
      tokens: {
        spacing: {
          sm: { value: '0.5rem', slug: '30', name: 'Small' },
          md: { value: '1rem', slug: '40', name: 'Medium' },
        },
        viewport: {
          mobile: { value: '500px' },
          tablet: { value: '800px' },
        },
      },
    };
    expect(generateTokensScss(snapshotConfig)).toBe(
      [
        '// Auto-generated by component2block — do not edit manually',
        '',
        '// Spacing',
        '$rds-spacing-sm: 0.5rem;',
        '$rds-spacing-md: 1rem;',
        '',
        '// Viewport',
        '$rds-viewport-mobile: 500px;',
        '$rds-viewport-tablet: 800px;',
        '',
        '// Viewport media queries',
        '// Matches the @mobile / @tablet breakpoints WordPress applies to block styles.',
        '',
        '@mixin mobile {',
        '  @media (width <= #{$rds-viewport-mobile}) {',
        '    @content;',
        '  }',
        '}',
        '',
        '@mixin tablet {',
        '  @media (#{$rds-viewport-mobile} < width <= #{$rds-viewport-tablet}) {',
        '    @content;',
        '  }',
        '}',
        '',
        '@mixin tablet-down {',
        '  @media (width <= #{$rds-viewport-tablet}) {',
        '    @content;',
        '  }',
        '}',
        '',
      ].join('\n'),
    );
  });
});

describe('generateTokensScss — viewport media-query mixins', () => {
  const build = (viewport: Record<string, { value: string }>, scssVars = ['viewport']) =>
    generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars,
      tokens: { viewport },
    })!;

  it('emits mobile as a max-width query', () => {
    const output = build({ mobile: { value: '500px' }, tablet: { value: '800px' } });
    expect(output).toContain('@mixin mobile {');
    expect(output).toContain('  @media (width <= #{$test-viewport-mobile}) {');
  });

  it('emits tablet as the band between the two breakpoints, matching WordPress', () => {
    const output = build({ mobile: { value: '500px' }, tablet: { value: '800px' } });
    expect(output).toContain('@mixin tablet {');
    expect(output).toContain(
      '  @media (#{$test-viewport-mobile} < width <= #{$test-viewport-tablet}) {',
    );
  });

  it('emits a tablet-down convenience mixin when both are defined', () => {
    const output = build({ mobile: { value: '500px' }, tablet: { value: '800px' } });
    expect(output).toContain('@mixin tablet-down {');
    expect(output).toContain('  @media (width <= #{$test-viewport-tablet}) {');
  });

  it('passes @content through every mixin', () => {
    const output = build({ mobile: { value: '500px' }, tablet: { value: '800px' } });
    expect(output.match(/@content;/g)).toHaveLength(3);
  });

  it('falls back to a single max-width query when only mobile is defined', () => {
    const output = build({ mobile: { value: '500px' } });
    expect(output).toContain('@mixin mobile {');
    expect(output).toContain('  @media (width <= #{$test-viewport-mobile}) {');
    expect(output).not.toContain('@mixin tablet {');
    expect(output).not.toContain('@mixin tablet-down {');
  });

  it('keeps the tablet name with a single max-width query when only tablet is defined', () => {
    const output = build({ tablet: { value: '800px' } });
    expect(output).toContain('@mixin tablet {');
    expect(output).toContain('  @media (width <= #{$test-viewport-tablet}) {');
    expect(output).not.toContain('@mixin mobile {');
    expect(output).not.toContain('@mixin tablet-down {');
  });

  it('emits no mixins when viewport is not opted into scssVars', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['spacing'],
      tokens: {
        spacing: { md: { value: '1rem' } },
        viewport: { mobile: { value: '500px' } },
      },
    })!;
    expect(output).not.toContain('@mixin');
    expect(output).not.toContain('Viewport media queries');
  });
});
