import { describe, it, expect } from 'vitest';
import { generateTokensJs, generateTokensDts } from '../src/generators/tokens-js.js';
import type { C2bConfig } from '../src/types.js';

const config: C2bConfig = {
  prefix: 'test',
  srcDir: 'src/styles',
  outputDir: 'dist/wp',
  bundleFonts: false,
  tokens: {
    colorPalette: {
      primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
      'primary-dark': { value: '#005a87' },
    },
    spacing: {
      sm: { value: '0.5rem', slug: 'small', name: 'Small' },
      md: { value: '1rem', slug: 'medium', name: 'Medium' },
    },
    fontFamily: {
      base: { value: 'sans-serif', name: 'Sans', slug: 'body' },
    },
    fontWeight: {
      normal: { value: '400' },
      bold: { value: '700' },
    },
    layout: {
      contentSize: { value: '645px' },
      wideSize: { value: '1340px' },
    },
    viewport: {
      mobile: { value: '500px' },
      tablet: { value: '800px' },
    },
  },
};

describe('generateTokensJs', () => {
  const output = generateTokensJs(config);

  it('includes the auto-generated header', () => {
    expect(output).toContain('Auto-generated by component2block');
  });

  it('does not include the v() helper', () => {
    expect(output).not.toContain('const v =');
    expect(output).not.toContain('var(');
  });

  it('exports a const named after the prefix with Tokens suffix', () => {
    expect(output).toContain('export const testTokens = {');
  });

  it('exports a default export', () => {
    expect(output).toContain('export default testTokens;');
  });

  it('emits color tokens as hardcoded values', () => {
    expect(output).toContain("        primary: '#0073aa'");
    expect(output).toContain("        primaryDark: '#005a87'");
  });

  it('emits spacing tokens as hardcoded values', () => {
    expect(output).toContain("        sm: '0.5rem'");
    expect(output).toContain("        md: '1rem'");
  });

  it('converts kebab cssSegment to camelCase for the category key', () => {
    expect(output).toContain('    fontFamily: {');
    expect(output).toContain('    fontWeight: {');
  });

  it('converts kebab token keys to camelCase', () => {
    expect(output).toContain("        primaryDark: '#005a87'");
  });

  it('emits fontFamily tokens as hardcoded values', () => {
    expect(output).toContain("        base: 'sans-serif'");
  });

  it('emits fontWeight tokens as hardcoded values', () => {
    expect(output).toContain("        normal: '400'");
    expect(output).toContain("        bold: '700'");
  });

  it('emits layout tokens with directMap key conversion', () => {
    expect(output).toContain("        contentSize: '645px'");
    expect(output).toContain("        wideSize: '1340px'");
  });

  it('emits viewport tokens', () => {
    expect(output).toContain("        mobile: '500px'");
    expect(output).toContain("        tablet: '800px'");
  });

  it('has no trailing comma on the last token in each category', () => {
    expect(output).toContain("        primaryDark: '#005a87'\n    }");
  });

  it('has no trailing comma on the last category', () => {
    expect(output).toContain("    }\n};");
  });

  it('skips categories with no tokens', () => {
    expect(output).not.toContain('colorGradient');
    expect(output).not.toContain('fontSize');
  });
});

describe('generateTokensJs — fluid font sizes emit clamp() values', () => {
  const fluidConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      fontSize: {
        medium: { value: '1.125rem', slug: 'medium', name: 'Medium', fluid: { min: '0.875rem', max: '1.125rem' } },
        static: { value: '0.75rem', slug: 'static', name: 'Static' },
      },
    },
  };

  const output = generateTokensJs(fluidConfig);

  it('emits clamp() for fluid tokens', () => {
    expect(output).toContain("        medium: 'clamp(");
  });

  it('emits raw value for non-fluid tokens', () => {
    expect(output).toContain("        static: '0.75rem'");
  });
});

describe('generateTokensJs — digit-leading keys produce valid identifiers', () => {
  const digitConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      spacing: {
        'x-small': { value: '0.5rem' },
        '2-x-small': { value: '0.25rem' },
        '3-x-large': { value: '4rem' },
      },
    },
  };

  const output = generateTokensJs(digitConfig);

  it('leaves non-digit keys unchanged', () => {
    expect(output).toContain("        xSmall: '0.5rem'");
  });

  it('moves leading digit after the first letter', () => {
    expect(output).toContain("        x2Small: '0.25rem'");
    expect(output).toContain("        x3Large: '4rem'");
  });

  it('does not produce identifiers starting with a digit', () => {
    expect(output).not.toMatch(/^\s+\d\w+:/m);
  });
});

describe('generateTokensJs — colorGradient uses gradient key', () => {
  const gradientConfig: C2bConfig = {
    prefix: 'ds',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorGradient: {
        'blue-to-teal': { value: 'linear-gradient(#00f, #0ff)' },
      },
    },
  };

  const output = generateTokensJs(gradientConfig);

  it('uses gradient (not colorGradient) as the JS category key', () => {
    expect(output).toContain('    gradient: {');
  });

  it('emits the hardcoded gradient value', () => {
    expect(output).toContain("        blueToTeal: 'linear-gradient(#00f, #0ff)'");
  });
});

describe('generateTokensJs — prefix used in export name', () => {
  const prefixConfig: C2bConfig = {
    prefix: 'rds',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorPalette: {
        primary: { value: '#cc0000', slug: 'primary', name: 'Primary' },
      },
    },
  };

  const output = generateTokensJs(prefixConfig);

  it('uses the prefix in the export name', () => {
    expect(output).toContain('export const rdsTokens = {');
    expect(output).toContain('export default rdsTokens;');
  });

  it('emits the hardcoded value', () => {
    expect(output).toContain("        primary: '#cc0000'");
  });
});

describe('generateTokensJs — hyphenated prefixes produce valid identifiers', () => {
  const hyphenConfig: C2bConfig = {
    prefix: 'design-system',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorPalette: { primary: { value: '#0073aa' } },
    },
  };

  it('camelCases the prefix in the named export', () => {
    const output = generateTokensJs(hyphenConfig);
    expect(output).toContain('export const designSystemTokens = {');
    expect(output).toContain('export default designSystemTokens;');
    expect(output).not.toContain('design-systemTokens');
  });

  it('camelCases the prefix in the .d.ts declaration', () => {
    const output = generateTokensDts(hyphenConfig);
    expect(output).toContain('export declare const designSystemTokens:');
    expect(output).toContain('export default designSystemTokens;');
    expect(output).not.toContain('design-systemTokens');
  });

  it('leaves an already-valid prefix untouched', () => {
    expect(generateTokensJs({ ...hyphenConfig, prefix: 'mylib' })).toContain(
      'export const mylibTokens = {',
    );
  });
});

// Compiles the generated module and hands back the token object, so a test can
// assert on real values instead of on substrings. Any syntax error in an emitted
// key or value throws here — which is the point: every assertion that reads a
// value through this helper is also a guard that the output actually parses.
function evalTokens(output: string): Record<string, Record<string, string>> {
  const body = output
    .replace(/^export const (\w+) = \{/m, 'const $1 = {')
    .replace(/^export default (\w+);$/m, 'return $1;');
  return new Function(body)() as Record<string, Record<string, string>>;
}

describe('generateTokensJs — emitted output is valid JavaScript', () => {
  it('parses the output for a representative config', () => {
    expect(() => evalTokens(generateTokensJs(config))).not.toThrow();
  });

  it('escapes single quotes so quoted font stacks survive', () => {
    const fontConfig: C2bConfig = {
      prefix: 'test',
      srcDir: 'src/styles',
      outputDir: 'dist/wp',
      bundleFonts: false,
      tokens: {
        fontFamily: {
          'inter-tight': { value: "'Inter Tight', system-ui, 'Segoe UI', roboto, sans-serif" },
        },
      },
    };

    const tokens = evalTokens(generateTokensJs(fontConfig));
    expect(tokens.fontFamily.interTight).toBe(
      "'Inter Tight', system-ui, 'Segoe UI', roboto, sans-serif",
    );
  });

  it('escapes backslashes before quotes, so both round-trip', () => {
    const escapeConfig: C2bConfig = {
      prefix: 'test',
      srcDir: 'src/styles',
      outputDir: 'dist/wp',
      bundleFonts: false,
      tokens: {
        fontFamily: { odd: { value: String.raw`a\b'c` } },
      },
    };

    expect(evalTokens(generateTokensJs(escapeConfig)).fontFamily.odd).toBe(String.raw`a\b'c`);
  });

  it('camelCases a hyphen sitting before a digit', () => {
    const digitConfig: C2bConfig = {
      prefix: 'test',
      srcDir: 'src/styles',
      outputDir: 'dist/wp',
      bundleFonts: false,
      tokens: {
        fontFamily: {
          'source-serif-4': { value: "'Source Serif 4', ui-serif, georgia, serif" },
        },
        spacing: { 'spacing-10': { value: '0.175rem' } },
      },
    };

    const tokens = evalTokens(generateTokensJs(digitConfig));
    expect(Object.keys(tokens.fontFamily)).toEqual(['sourceSerif4']);
    expect(Object.keys(tokens.spacing)).toEqual(['spacing10']);
  });

  it('quotes keys that are not valid identifiers', () => {
    const zConfig: C2bConfig = {
      prefix: 'test',
      srcDir: 'src/styles',
      outputDir: 'dist/wp',
      bundleFonts: false,
      tokens: {
        zIndex: { '100': { value: '100' }, '200': { value: '200' } },
      },
    };

    const output = generateTokensJs(zConfig);
    expect(output).toContain("        '100': '100'");
    expect(evalTokens(output).z).toEqual({ '100': '100', '200': '200' });
  });
});
