import { describe, it, expect } from 'vitest';
import { generateTokensCss } from '../src/generators/tokens-css.js';
import type { C2bConfig } from '../src/types.js';

const config: C2bConfig = {
  prefix: 'test',
  srcDir: 'src/styles',

  themeDir: 'dist/wp',
  bundleFonts: false,
  tokens: {
    colorPalette: {
      primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
      'primary-hover': { value: '#005a87' },
    },
    spacing: {
      md: { value: '1rem', slug: '40', name: 'Medium' },
    },
    fontFamily: {
      base: { value: 'sans-serif', name: 'Sans', slug: 'body' },
    },
    fontSize: {
      sm: { value: '0.875rem', slug: 'small', name: 'Small' },
      xs: { value: '0.75rem' },
    },
    zIndex: {
      modal: { value: '300' },
    },
  },
};

describe('generateTokensCss', () => {
  const output = generateTokensCss(config);

  it('includes the auto-generated header', () => {
    expect(output).toContain('Auto-generated by component2block');
  });

  it('generates correct color variables', () => {
    expect(output).toContain('--test--color-primary: #0073aa;');
    expect(output).toContain('--test--color-primary-hover: #005a87;');
  });

  it('generates correct spacing variables', () => {
    expect(output).toContain('--test--spacing-md: 1rem;');
  });

  it('generates correct font-family variables', () => {
    expect(output).toContain('--test--font-family-base: sans-serif;');
  });

  it('generates correct font-size variables', () => {
    expect(output).toContain('--test--font-size-sm: 0.875rem;');
    expect(output).toContain('--test--font-size-xs: 0.75rem;');
  });

  it('generates correct z-index variables', () => {
    expect(output).toContain('--test--z-modal: 300;');
  });

  it('groups tokens by category with comments', () => {
    expect(output).toContain('/* Colors */');
    expect(output).toContain('/* Spacing */');
    expect(output).toContain('/* Z-Index */');
  });

  it('wraps in :root selector', () => {
    expect(output).toContain(':root {');
    expect(output).toContain('}');
  });

  it('uses hardcoded values for all tokens (no var() wrappers)', () => {
    expect(output).not.toContain('var(');
  });
});

describe('generateTokensCss — layout tokens', () => {
  const layoutConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    themeDir: 'dist/wp',
  bundleFonts: false,
    tokens: {
      layout: {
        contentSize: { value: '645px' },
        wideSize: { value: '1340px' },
      },
    },
  };

  const output = generateTokensCss(layoutConfig);

  it('generates layout CSS variables', () => {
    expect(output).toContain('--test--layout-content-size: 645px;');
    expect(output).toContain('--test--layout-wide-size: 1340px;');
  });

  it('groups layout tokens with a comment', () => {
    expect(output).toContain('/* Layout */');
  });
});

describe('generateTokensCss — fluid font sizes', () => {
  const fluidConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    themeDir: 'dist/wp',
  bundleFonts: false,
    tokens: {
      fontSize: {
        medium: {
          value: '1.125rem',
          slug: 'medium',
          name: 'Medium',
          fluid: { min: '0.875rem', max: '1.125rem' },
        },
        large: {
          value: '1.75rem',
          slug: 'large',
          name: 'Large',
          fluid: { min: '1.25rem', max: '1.75rem' },
        },
        static: {
          value: '0.75rem',
          slug: 'static',
          name: 'Static',
        },
      },
    },
  };

  const output = generateTokensCss(fluidConfig);

  it('generates clamp() for fluid font sizes using WP-compatible formula shape', () => {
    // (1.125 - 0.875) / (1600/1600 - 320/1600) = 0.25 / 0.8 = 0.313 (3dp)
    expect(output).toContain(
      '--test--font-size-medium: clamp(0.875rem, 0.875rem + ((1vw - 0.2rem) * 0.313), 1.125rem);'
    );
  });

  it('uses correct rate for larger fluid sizes', () => {
    // (1.75 - 1.25) / 0.8 = 0.625
    expect(output).toContain(
      '--test--font-size-large: clamp(1.25rem, 1.25rem + ((1vw - 0.2rem) * 0.625), 1.75rem);'
    );
  });

  it('uses static value when no fluid is defined', () => {
    expect(output).toContain('--test--font-size-static: 0.75rem;');
  });

  /**
   * Regression for the fluid-clamp math bug: earlier output used a unitless
   * denominator and a unitless scaling constant, which collapsed the fluid
   * adjustment to a fraction of a pixel — tokens never actually scaled.
   *
   * This test extracts the emitted clamp formula, plugs in several viewport
   * widths, and asserts the result actually interpolates between min and max.
   */
  it('emitted clamp() formula scales between min and max across viewport widths', () => {
    const clampRegex = /--test--font-size-medium: (clamp\([^;]+\));/;
    const match = output.match(clampRegex);
    expect(match).not.toBeNull();
    const expr = match![1];

    // Parse: clamp(<min>rem, <min>rem + ((1vw - <minVwRem>rem) * <rate>), <max>rem)
    const parts = expr.match(
      /^clamp\(([\d.]+)rem, \1rem \+ \(\(1vw - ([\d.]+)rem\) \* ([\d.]+)\), ([\d.]+)rem\)$/,
    );
    expect(parts).not.toBeNull();
    const [, minRem, minVwRem, rate, maxRem] = parts!.map(Number);

    // Default viewport anchors are 320px / 1600px.
    // minVwRem should equal 320/1600 = 0.2 (1vw at 320px viewport, in rem at 16px root).
    expect(minVwRem).toBeCloseTo(0.2, 4);
    // rate should satisfy: min + (maxVwRem - minVwRem) * rate ≈ max
    //   0.8 * rate ≈ 0.25  →  rate ≈ 0.313 (3dp rounding to match WP)
    expect(rate).toBeCloseTo((maxRem - minRem) / 0.8, 2);

    // Evaluate the clamp formula at a given viewport width (px), matching how
    // a browser would: 1vw = viewportPx / 100 = viewportPx / 1600 rem (at a
    // 16px root font size).
    const ROOT = 16;
    const evalClamp = (vwPx: number): number => {
      const oneVwInRem = vwPx / 100 / ROOT;
      const middle = minRem + (oneVwInRem - minVwRem) * rate;
      return Math.max(minRem, Math.min(maxRem, middle));
    };

    // At or below minViewport → pinned to min
    expect(evalClamp(320)).toBeCloseTo(minRem, 4);
    expect(evalClamp(0)).toBeCloseTo(minRem, 4);

    // At or above maxViewport → pinned to max
    expect(evalClamp(1600)).toBeCloseTo(maxRem, 4);
    expect(evalClamp(2400)).toBeCloseTo(maxRem, 4);

    // Between anchors → strictly interpolates (strict monotonic growth)
    const at768 = evalClamp(768);
    const at1200 = evalClamp(1200);
    expect(at768).toBeGreaterThan(minRem);
    expect(at768).toBeLessThan(maxRem);
    expect(at1200).toBeGreaterThan(at768);
    expect(at1200).toBeLessThan(maxRem);

    // Midpoint viewport should land close to halfway between min and max.
    // Precision reduced to 2dp to account for 3dp rate rounding (matching WP).
    const midVw = (320 + 1600) / 2; // 960px
    expect(evalClamp(midVw)).toBeCloseTo(minRem + (maxRem - minRem) / 2, 2);
  });

  /**
   * Verify custom viewport anchors from config propagate to the emitted formula.
   */
  it('honors custom fluid viewport anchors from config', () => {
    const customConfig: C2bConfig = {
      ...fluidConfig,
      fluid: { minViewport: '320px', maxViewport: '1280px' },
    };
    const customOutput = generateTokensCss(customConfig);
    // minVwRem = 320/1600 = 0.2, maxVwRem = 1280/1600 = 0.8
    // rate = (1.125 - 0.875) / (0.8 - 0.2) = 0.25 / 0.6 = 0.417 (3dp)
    expect(customOutput).toContain(
      '--test--font-size-medium: clamp(0.875rem, 0.875rem + ((1vw - 0.2rem) * 0.417), 1.125rem);',
    );
  });

  /**
   * Byte-for-byte match with the shape WordPress emits from theme.json fluid
   * typography. This test is pinned to the exact numeric values from the bug
   * report so the fix is obvious if it ever regresses.
   */
  it('matches WordPress reference output for 320/1280 anchors (1rem → 1.125rem)', () => {
    const wpMatchConfig: C2bConfig = {
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
  bundleFonts: false,
      tokens: {
        fontSize: {
          body: {
            value: '1.125rem',
            slug: 'body',
            name: 'Body',
            fluid: { min: '1rem', max: '1.125rem' },
          },
        },
      },
      fluid: { minViewport: '320px', maxViewport: '1280px' },
    };
    const out = generateTokensCss(wpMatchConfig);
    // Reference from WP's own :root emission:
    //   clamp(1rem, 1rem + ((1vw - 0.2rem) * 0.208), 1.125rem)
    // Now matches WP exactly with 3-decimal rounding.
    expect(out).toContain(
      '--test--font-size-body: clamp(1rem, 1rem + ((1vw - 0.2rem) * 0.208), 1.125rem);',
    );
  });
});
