import { describe, it, expect } from 'vitest';
import { generateTokensJs } from '../src/generators/tokens-js.js';
import type { C2bConfig } from '../src/types.js';

const config: C2bConfig = {
  prefix: 'test',
  srcDir: 'src/styles',
  outputDir: 'dist/wp',
  bundleFonts: false,
  tokens: {
    colorPalette: {
      primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
      'primary-dark': { value: '#005a87' },
    },
    spacing: {
      sm: { value: '0.5rem', slug: 'small', name: 'Small' },
      md: { value: '1rem', slug: 'medium', name: 'Medium' },
    },
    fontFamily: {
      base: { value: 'sans-serif', name: 'Sans', slug: 'body' },
    },
    fontWeight: {
      normal: { value: '400' },
      bold: { value: '700' },
    },
    layout: {
      contentSize: { value: '645px' },
      wideSize: { value: '1340px' },
    },
  },
};

describe('generateTokensJs', () => {
  const output = generateTokensJs(config);

  it('includes the auto-generated header', () => {
    expect(output).toContain('Auto-generated by component2block');
  });

  it('does not include the v() helper', () => {
    expect(output).not.toContain('const v =');
    expect(output).not.toContain('var(');
  });

  it('exports a const named after the prefix with Tokens suffix', () => {
    expect(output).toContain('export const testTokens = {');
  });

  it('exports a default export', () => {
    expect(output).toContain('export default testTokens;');
  });

  it('emits color tokens as hardcoded values', () => {
    expect(output).toContain("        primary: '#0073aa'");
    expect(output).toContain("        primaryDark: '#005a87'");
  });

  it('emits spacing tokens as hardcoded values', () => {
    expect(output).toContain("        sm: '0.5rem'");
    expect(output).toContain("        md: '1rem'");
  });

  it('converts kebab cssSegment to camelCase for the category key', () => {
    expect(output).toContain('    fontFamily: {');
    expect(output).toContain('    fontWeight: {');
  });

  it('converts kebab token keys to camelCase', () => {
    expect(output).toContain("        primaryDark: '#005a87'");
  });

  it('emits fontFamily tokens as hardcoded values', () => {
    expect(output).toContain("        base: 'sans-serif'");
  });

  it('emits fontWeight tokens as hardcoded values', () => {
    expect(output).toContain("        normal: '400'");
    expect(output).toContain("        bold: '700'");
  });

  it('emits layout tokens with directMap key conversion', () => {
    expect(output).toContain("        contentSize: '645px'");
    expect(output).toContain("        wideSize: '1340px'");
  });

  it('has no trailing comma on the last token in each category', () => {
    expect(output).toContain("        primaryDark: '#005a87'\n    }");
  });

  it('has no trailing comma on the last category', () => {
    expect(output).toContain("    }\n};");
  });

  it('skips categories with no tokens', () => {
    expect(output).not.toContain('colorGradient');
    expect(output).not.toContain('fontSize');
  });
});

describe('generateTokensJs — fluid font sizes emit clamp() values', () => {
  const fluidConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      fontSize: {
        medium: { value: '1.125rem', slug: 'medium', name: 'Medium', fluid: { min: '0.875rem', max: '1.125rem' } },
        static: { value: '0.75rem', slug: 'static', name: 'Static' },
      },
    },
  };

  const output = generateTokensJs(fluidConfig);

  it('emits clamp() for fluid tokens', () => {
    expect(output).toContain("        medium: 'clamp(");
  });

  it('emits raw value for non-fluid tokens', () => {
    expect(output).toContain("        static: '0.75rem'");
  });
});

describe('generateTokensJs — mediaQuery excluded', () => {
  const mqConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorPalette: {
        white: { value: '#fff' },
      },
      mediaQuery: {
        sm: { value: '640px' },
      },
    },
  };

  it('does not emit a mediaQuery category (scssOnly)', () => {
    const output = generateTokensJs(mqConfig);
    expect(output).not.toContain('mediaQuery');
    expect(output).not.toContain('media-query');
  });
});

describe('generateTokensJs — digit-leading keys produce valid identifiers', () => {
  const digitConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      spacing: {
        'x-small': { value: '0.5rem' },
        '2-x-small': { value: '0.25rem' },
        '3-x-large': { value: '4rem' },
      },
    },
  };

  const output = generateTokensJs(digitConfig);

  it('leaves non-digit keys unchanged', () => {
    expect(output).toContain("        xSmall: '0.5rem'");
  });

  it('moves leading digit after the first letter', () => {
    expect(output).toContain("        x2Small: '0.25rem'");
    expect(output).toContain("        x3Large: '4rem'");
  });

  it('does not produce identifiers starting with a digit', () => {
    expect(output).not.toMatch(/^\s+\d\w+:/m);
  });
});

describe('generateTokensJs — colorGradient uses gradient key', () => {
  const gradientConfig: C2bConfig = {
    prefix: 'ds',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorGradient: {
        'blue-to-teal': { value: 'linear-gradient(#00f, #0ff)' },
      },
    },
  };

  const output = generateTokensJs(gradientConfig);

  it('uses gradient (not colorGradient) as the JS category key', () => {
    expect(output).toContain('    gradient: {');
  });

  it('emits the hardcoded gradient value', () => {
    expect(output).toContain("        blueToTeal: 'linear-gradient(#00f, #0ff)'");
  });
});

describe('generateTokensJs — prefix used in export name', () => {
  const prefixConfig: C2bConfig = {
    prefix: 'rds',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorPalette: {
        primary: { value: '#cc0000', slug: 'primary', name: 'Primary' },
      },
    },
  };

  const output = generateTokensJs(prefixConfig);

  it('uses the prefix in the export name', () => {
    expect(output).toContain('export const rdsTokens = {');
    expect(output).toContain('export default rdsTokens;');
  });

  it('emits the hardcoded value', () => {
    expect(output).toContain("        primary: '#cc0000'");
  });
});
