import { describe, it, expect } from 'vitest';
import { generateTokensScss } from '../src/generators/tokens-scss.js';
import type { C2bConfig } from '../src/types.js';

describe('generateTokensScss — opt-in via scssVars', () => {
  const baseConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    themeDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorPalette: {
        primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
      },
      spacing: {
        md: { value: '1rem', slug: '40', name: 'Medium' },
      },
      mediaQuery: {
        sm: { value: '600px' },
        md: { value: '784px' },
        lg: { value: '1024px' },
      },
    },
  };

  it('returns null when scssVars is empty or unset', () => {
    expect(generateTokensScss(baseConfig)).toBeNull();
    expect(generateTokensScss({ ...baseConfig, scssVars: [] })).toBeNull();
  });

  it('emits only selected categories', () => {
    const output = generateTokensScss({ ...baseConfig, scssVars: ['mediaQuery'] });
    expect(output).not.toBeNull();
    expect(output).toContain('// Media Queries');
    expect(output).toContain('$test-media-query-sm: 600px;');
    expect(output).toContain('$test-media-query-md: 784px;');
    expect(output).toContain('$test-media-query-lg: 1024px;');
    expect(output).not.toContain('// Colors');
    expect(output).not.toContain('// Spacing');
    expect(output).not.toContain('color-primary');
  });

  it('supports multiple categories in registry order (not config order)', () => {
    const output = generateTokensScss({
      ...baseConfig,
      // Ask for mediaQuery first, but expect colorPalette first in output
      // because CATEGORY_ORDER puts colors ahead of mediaQuery.
      scssVars: ['mediaQuery', 'colorPalette', 'spacing'],
    })!;
    const colorIdx = output.indexOf('// Colors');
    const spacingIdx = output.indexOf('// Spacing');
    const mqIdx = output.indexOf('// Media Queries');
    expect(colorIdx).toBeGreaterThan(0);
    expect(spacingIdx).toBeGreaterThan(colorIdx);
    expect(mqIdx).toBeGreaterThan(spacingIdx);
  });

  it('includes the auto-generated header', () => {
    const output = generateTokensScss({ ...baseConfig, scssVars: ['mediaQuery'] })!;
    expect(output).toContain('// Auto-generated by component2block');
  });

  it('does not wrap in :root or any selector', () => {
    const output = generateTokensScss({ ...baseConfig, scssVars: ['mediaQuery'] })!;
    expect(output).not.toContain(':root');
    expect(output).not.toContain('{');
    expect(output).not.toContain('}');
  });

  it('uses single-dash separators, not CSS custom property --', () => {
    const output = generateTokensScss({ ...baseConfig, scssVars: ['colorPalette'] })!;
    expect(output).not.toContain('--');
  });

  it('skips selected categories that have no tokens defined', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['mediaQuery', 'spacing'],
      tokens: {
        mediaQuery: {
          sm: { value: '600px' },
        },
      },
    })!;
    expect(output).toContain('$test-media-query-sm: 600px;');
    expect(output).not.toContain('// Spacing');
  });
});

describe('generateTokensScss — category-specific formatting', () => {
  it('includes cssOnly tokens for opted-in categories', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['colorPalette'],
      tokens: {
        colorPalette: {
          primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
          'primary-hover': { value: '#005a87', cssOnly: true },
        },
      },
    })!;
    expect(output).toContain('$test-color-primary: #0073aa;');
    expect(output).toContain('$test-color-primary-hover: #005a87;');
  });

  it('applies camelToKebab conversion for layout keys', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['layout'],
      tokens: {
        layout: {
          contentSize: { value: '645px' },
          wideSize: { value: '1340px' },
        },
      },
    })!;
    expect(output).toContain('$test-layout-content-size: 645px;');
    expect(output).toContain('$test-layout-wide-size: 1340px;');
  });

  it('emits fluid clamp() identical to tokens.css', () => {
    const output = generateTokensScss({
      prefix: 'test',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['fontSize'],
      tokens: {
        fontSize: {
          medium: {
            value: '1.125rem',
            slug: 'medium',
            name: 'Medium',
            fluid: { min: '0.875rem', max: '1.125rem' },
          },
          static: { value: '0.75rem', slug: 'static', name: 'Static' },
        },
      },
    })!;
    expect(output).toContain(
      '$test-font-size-medium: clamp(0.875rem, 0.875rem + ((1vw - 0.2rem) * 0.313), 1.125rem);',
    );
    expect(output).toContain('$test-font-size-static: 0.75rem;');
  });
});

describe('generateTokensScss — snapshot', () => {
  it('matches the expected file shape for a mediaQuery + spacing config', () => {
    const snapshotConfig: C2bConfig = {
      prefix: 'rds',
      srcDir: 'src/styles',
      themeDir: 'dist/wp',
      bundleFonts: false,
      scssVars: ['spacing', 'mediaQuery'],
      tokens: {
        spacing: {
          sm: { value: '0.5rem', slug: '30', name: 'Small' },
          md: { value: '1rem', slug: '40', name: 'Medium' },
        },
        mediaQuery: {
          sm: { value: '600px' },
          md: { value: '784px' },
          lg: { value: '1024px' },
          xl: { value: '1280px' },
        },
      },
    };
    expect(generateTokensScss(snapshotConfig)).toBe(
      [
        '// Auto-generated by component2block — do not edit manually',
        '',
        '// Spacing',
        '$rds-spacing-sm: 0.5rem;',
        '$rds-spacing-md: 1rem;',
        '',
        '// Media Queries',
        '$rds-media-query-sm: 600px;',
        '$rds-media-query-md: 784px;',
        '$rds-media-query-lg: 1024px;',
        '$rds-media-query-xl: 1280px;',
        '',
      ].join('\n'),
    );
  });
});
