import { describe, it, expect } from 'vitest';
import { generateTokensJs } from '../src/generators/tokens-js.js';
import type { C2bConfig } from '../src/types.js';

const config: C2bConfig = {
  prefix: 'test',
  srcDir: 'src/styles',
  outputDir: 'dist/wp',
  bundleFonts: false,
  tokens: {
    colorPalette: {
      primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
      'primary-dark': { value: '#005a87' },
    },
    spacing: {
      sm: { value: '0.5rem', slug: 'small', name: 'Small' },
      md: { value: '1rem', slug: 'medium', name: 'Medium' },
    },
    fontFamily: {
      base: { value: 'sans-serif', name: 'Sans', slug: 'body' },
    },
    fontWeight: {
      normal: { value: '400' },
      bold: { value: '700' },
    },
    layout: {
      contentSize: { value: '645px' },
      wideSize: { value: '1340px' },
    },
  },
};

describe('generateTokensJs', () => {
  const output = generateTokensJs(config);

  it('includes the auto-generated header', () => {
    expect(output).toContain('Auto-generated by component2block');
  });

  it('declares the v helper', () => {
    expect(output).toContain('const v = (name) => `var(${name})`;');
  });

  it('exports a const named after the prefix with Tokens suffix', () => {
    expect(output).toContain('export const testTokens = {');
  });

  it('exports a default export', () => {
    expect(output).toContain('export default testTokens;');
  });

  it('emits color tokens under the color key', () => {
    expect(output).toContain("        primary: v('--test--color-primary')");
    expect(output).toContain("        primaryDark: v('--test--color-primary-dark')");
  });

  it('emits spacing tokens under the spacing key', () => {
    expect(output).toContain("        sm: v('--test--spacing-sm')");
    expect(output).toContain("        md: v('--test--spacing-md')");
  });

  it('converts kebab cssSegment to camelCase for the category key', () => {
    expect(output).toContain('    fontFamily: {');
    expect(output).toContain('    fontWeight: {');
  });

  it('converts kebab token keys to camelCase', () => {
    expect(output).toContain("        primaryDark: v('--test--color-primary-dark')");
  });

  it('emits fontFamily tokens', () => {
    expect(output).toContain("        base: v('--test--font-family-base')");
  });

  it('emits fontWeight tokens', () => {
    expect(output).toContain("        normal: v('--test--font-weight-normal')");
    expect(output).toContain("        bold: v('--test--font-weight-bold')");
  });

  it('emits layout tokens with directMap key conversion', () => {
    expect(output).toContain("        contentSize: v('--test--layout-content-size')");
    expect(output).toContain("        wideSize: v('--test--layout-wide-size')");
  });

  it('has no trailing comma on the last token in each category', () => {
    // last color token is primary-dark → primaryDark, no trailing comma
    expect(output).toContain("        primaryDark: v('--test--color-primary-dark')\n    }");
  });

  it('has no trailing comma on the last category', () => {
    expect(output).toContain("    }\n};");
  });

  it('skips categories with no tokens', () => {
    expect(output).not.toContain('colorGradient');
    expect(output).not.toContain('fontSize');
  });
});

describe('generateTokensJs — mediaQuery excluded', () => {
  const mqConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorPalette: {
        white: { value: '#fff' },
      },
      mediaQuery: {
        sm: { value: '640px' },
      },
    },
  };

  it('does not emit a mediaQuery category (scssOnly)', () => {
    const output = generateTokensJs(mqConfig);
    expect(output).not.toContain('mediaQuery');
    expect(output).not.toContain('media-query');
  });
});

describe('generateTokensJs — digit-leading keys produce valid identifiers', () => {
  const digitConfig: C2bConfig = {
    prefix: 'test',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      spacing: {
        'x-small': { value: '0.5rem' },
        '2-x-small': { value: '0.25rem' },
        '3-x-large': { value: '4rem' },
      },
    },
  };

  const output = generateTokensJs(digitConfig);

  it('leaves non-digit keys unchanged', () => {
    expect(output).toContain("        xSmall: v('--test--spacing-x-small')");
  });

  it('moves leading digit after the first letter', () => {
    expect(output).toContain("        x2Small: v('--test--spacing-2-x-small')");
    expect(output).toContain("        x3Large: v('--test--spacing-3-x-large')");
  });

  it('does not produce identifiers starting with a digit', () => {
    expect(output).not.toMatch(/^\s+\d\w+:/m);
  });
});

describe('generateTokensJs — colorGradient uses gradient key', () => {
  const gradientConfig: C2bConfig = {
    prefix: 'ds',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorGradient: {
        'blue-to-teal': { value: 'linear-gradient(#00f, #0ff)' },
      },
    },
  };

  const output = generateTokensJs(gradientConfig);

  it('uses gradient (not colorGradient) as the JS category key', () => {
    expect(output).toContain('    gradient: {');
  });

  it('emits the correct var name', () => {
    expect(output).toContain("        blueToTeal: v('--ds--gradient-blue-to-teal')");
  });
});

describe('generateTokensJs — prefix used in export name and var names', () => {
  const prefixConfig: C2bConfig = {
    prefix: 'rds',
    srcDir: 'src/styles',
    outputDir: 'dist/wp',
    bundleFonts: false,
    tokens: {
      colorPalette: {
        primary: { value: '#cc0000', slug: 'primary', name: 'Primary' },
      },
    },
  };

  const output = generateTokensJs(prefixConfig);

  it('uses the prefix in the export name', () => {
    expect(output).toContain('export const rdsTokens = {');
    expect(output).toContain('export default rdsTokens;');
  });

  it('uses the prefix in var names', () => {
    expect(output).toContain("v('--rds--color-primary')");
  });
});
