import { describe, it, expect } from 'vitest';
import { generateTypographyCss } from '../src/generators/typography-css.js';
import type { C2bConfig } from '../src/types.js';

const baseConfig: C2bConfig = {
  prefix: 'rds',
  srcDir: 'src/styles',
  themeDir: 'dist/wp',
  bundleFonts: false,
  themeable: false,
  tokens: {
    spacing: {
      'x-small': { value: '0.5rem', slug: '20', name: 'X Small' },
      small: { value: '0.75rem', slug: '30', name: 'Small' },
      medium: { value: '1rem', slug: '40', name: 'Medium' },
      large: { value: '1.5rem', slug: '60', name: 'Large' },
      'x-large': { value: '2.25rem', slug: '70', name: 'X Large' },
      '2x-large': { value: '3rem', slug: '80', name: '2X Large' },
    },
  },
};

describe('generateTypographyCss', () => {
  it('returns null when no baseStyles', () => {
    const result = generateTypographyCss(baseConfig);
    expect(result).toBeNull();
  });

  it('returns null when baseStyles has no flow-spacing properties', () => {
    const config: C2bConfig = {
      ...baseConfig,
      baseStyles: {
        body: { color: 'inherit' },
        spacing: { blockGap: 'medium' },
      },
    };
    const result = generateTypographyCss(config);
    expect(result).toBeNull();
  });

  it('emits the auto-generated header', () => {
    const config: C2bConfig = {
      ...baseConfig,
      baseStyles: { h2: { marginBlockStart: 'x-large' } },
    };
    const result = generateTypographyCss(config)!;
    expect(result).toContain('Auto-generated by component2block');
  });

  it('emits all heading top-margin rules when configured', () => {
    const config: C2bConfig = {
      ...baseConfig,
      baseStyles: {
        h1: { marginBlockStart: '2x-large' },
        h2: { marginBlockStart: 'x-large' },
        h3: { marginBlockStart: 'large' },
        h4: { marginBlockStart: 'large' },
        h5: { marginBlockStart: 'medium' },
        h6: { marginBlockStart: 'medium' },
      },
    };
    const result = generateTypographyCss(config)!;
    expect(result).toContain(':where(.is-layout-constrained) > * + h1 {');
    expect(result).toContain('  margin-block-start: var(--rds--spacing-2x-large);');
    expect(result).toContain(':where(.is-layout-constrained) > * + h6 {');
    expect(result).toContain('  margin-block-start: var(--rds--spacing-medium);');
  });

  it('emits the after-heading rule when spacing.afterHeading is set', () => {
    const config: C2bConfig = {
      ...baseConfig,
      baseStyles: { spacing: { afterHeading: 'small' } },
    };
    const result = generateTypographyCss(config)!;
    expect(result).toContain(
      ':where(.is-layout-constrained) > :where(h1, h2, h3, h4, h5, h6) + * {',
    );
    expect(result).toContain('  margin-block-start: var(--rds--spacing-small);');
  });

  it('emits the li + li rule when spacing.listItem is set', () => {
    const config: C2bConfig = {
      ...baseConfig,
      baseStyles: { spacing: { listItem: 'x-small' } },
    };
    const result = generateTypographyCss(config)!;
    expect(result).toContain('li + li {');
    expect(result).toContain('  margin-block-start: var(--rds--spacing-x-small);');
  });

  it('omits sections that are not configured', () => {
    const config: C2bConfig = {
      ...baseConfig,
      baseStyles: { h2: { marginBlockStart: 'x-large' } },
    };
    const result = generateTypographyCss(config)!;
    expect(result).toContain('> * + h2 {');
    expect(result).not.toContain('> * + h3 {');
    expect(result).not.toContain('h1, h2, h3, h4, h5, h6) + *');
    expect(result).not.toContain('li + li');
  });

  it('passes raw values through unchanged', () => {
    const config: C2bConfig = {
      ...baseConfig,
      baseStyles: {
        h2: { marginBlockStart: '2.5rem' },
        spacing: { afterHeading: '0.5rem', listItem: '0.25rem' },
      },
    };
    const result = generateTypographyCss(config)!;
    expect(result).toContain('  margin-block-start: 2.5rem;');
    expect(result).toContain('  margin-block-start: 0.5rem;');
    expect(result).toContain('  margin-block-start: 0.25rem;');
  });

  it('output ends with a trailing newline', () => {
    const config: C2bConfig = {
      ...baseConfig,
      baseStyles: { h2: { marginBlockStart: 'x-large' } },
    };
    const result = generateTypographyCss(config)!;
    expect(result.endsWith('\n')).toBe(true);
  });
});
