import type { C2bConfig, BaseStyleElementDef } from '../types.js';
import { ELEMENT_REGISTRY, TYPOGRAPHY_PROPERTIES, camelToKebab } from '../types.js';
import { resolveBaseStyleValueForScss, ensureFontStyle } from '../config.js';

/**
 * Emit base-styles.css — per-element typography and color rules. Layout
 * utilities (block-gap, layout-constrained, has-global-padding, alignfull)
 * live in layout.css; flow-spacing rules (heading top margins, after-heading,
 * li + li) live in typography.css.
 *
 * Returns null when no element styling is configured.
 */
export function generateBaseStylesCss(config: C2bConfig): string | null {
  if (!config.baseStyles) return null;

  const { baseStyles, prefix, tokens } = config;
  const lines: string[] = [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
  ];

  // Body typography — wrapped in body { } since `body` isn't in the registry
  // (it has special theme.json handling, but its CSS rule is just typography).
  if (baseStyles.body) {
    lines.push('body {');
    appendDeclarations(lines, baseStyles.body, prefix, tokens, '  ');
    lines.push('}');
  }

  // Per-element rules from the registry — heading group, h1–h6, caption, button, link
  for (const def of ELEMENT_REGISTRY) {
    const elementDef = baseStyles[def.key];
    if (!elementDef) continue;

    // Individual headings get fontStyle: 'normal' default to neutralize browser italics.
    const withDefaults = def.isHeading ? ensureFontStyle(elementDef) : elementDef;

    lines.push('');
    lines.push(`${def.cssSelector} {`);
    appendDeclarations(lines, withDefaults, prefix, tokens, '  ');
    lines.push('}');

    // Hover pseudo-class (link)
    if (def.hoverCssSelector && elementDef.hoverColor !== undefined) {
      const resolvedHoverColor = resolveBaseStyleValueForScss(elementDef.hoverColor, 'hoverColor', prefix, tokens);
      lines.push('');
      lines.push(`${def.hoverCssSelector} {`);
      lines.push(`  color: ${resolvedHoverColor};`);
      lines.push('}');
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Append typography + color CSS declarations for an element definition.
 * Driven by TYPOGRAPHY_PROPERTIES so output order is centralized.
 */
function appendDeclarations(
  lines: string[],
  def: BaseStyleElementDef,
  prefix: string,
  tokens: C2bConfig['tokens'],
  indent: string,
): void {
  for (const prop of TYPOGRAPHY_PROPERTIES) {
    const value = def[prop];
    if (value === undefined) continue;
    const cssProperty = camelToKebab(prop);
    const resolvedValue = resolveBaseStyleValueForScss(value, prop, prefix, tokens);
    lines.push(`${indent}${cssProperty}: ${resolvedValue};`);
  }

  if (def.color !== undefined) {
    const resolvedValue = resolveBaseStyleValueForScss(def.color, 'color', prefix, tokens);
    lines.push(`${indent}color: ${resolvedValue};`);
  }
  if (def.background !== undefined) {
    const resolvedValue = resolveBaseStyleValueForScss(def.background, 'background', prefix, tokens);
    lines.push(`${indent}background-color: ${resolvedValue};`);
  }
}
