import type { C2bConfig, BaseStylesSpacingPadding, BaseStylesSpacing } from '../types.js';
import { resolveBaseStyleValueForScss } from '../config.js';

const PADDING_SIDES = ['top', 'right', 'bottom', 'left'] as const;

/**
 * Emit layout.css — root padding/block-gap CSS variables on `body` plus the
 * layout-utility rules (block-gap on constrained/flex/grid, layout constraint
 * for content/wide widths, has-global-padding helpers, alignfull bleed).
 *
 * Per-element typography lives in base-styles.css; flow-spacing rules live in
 * typography.css. This file is the layout-only output.
 *
 * Returns null when no layout-relevant config is present.
 */
export function generateLayoutCss(config: C2bConfig): string | null {
  const { baseStyles, prefix, tokens } = config;

  const hasSpacingPadding = !!baseStyles?.spacing?.padding;
  const hasBlockGap = !!baseStyles?.spacing?.blockGap;
  const hasLayoutTokens = !!tokens.layout;

  if (!hasSpacingPadding && !hasBlockGap && !hasLayoutTokens) {
    return null;
  }

  const lines: string[] = [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
  ];

  // Body block — root padding vars + block-gap var. Used by .has-global-padding
  // and the > * + * block-gap rule below.
  if (hasSpacingPadding || hasBlockGap) {
    lines.push('body {');
    if (baseStyles?.spacing?.padding) {
      appendRootPaddingVars(lines, baseStyles.spacing.padding, prefix, tokens);
    }
    if (baseStyles?.spacing?.blockGap) {
      appendBlockGapVar(lines, baseStyles.spacing, prefix, tokens);
    }
    lines.push('}');
  }

  if (hasBlockGap) {
    appendBlockGapRules(lines, prefix);
  }

  if (hasLayoutTokens) {
    appendLayoutConstraintRules(lines, prefix, tokens);
  }

  if (hasSpacingPadding) {
    lines.push('');
    lines.push('.has-global-padding {');
    lines.push(`  padding-right: var(--${prefix}--root-padding-right);`);
    lines.push(`  padding-left: var(--${prefix}--root-padding-left);`);
    lines.push('}');

    lines.push('');
    lines.push('.has-global-padding > .alignfull {');
    lines.push('  max-width: none;');
    lines.push(`  margin-right: calc(var(--${prefix}--root-padding-right) * -1);`);
    lines.push(`  margin-left: calc(var(--${prefix}--root-padding-left) * -1);`);
    lines.push('}');

    lines.push('');
    lines.push('.has-global-padding > .alignfull > .has-global-padding {');
    lines.push(`  padding-right: var(--${prefix}--root-padding-right);`);
    lines.push(`  padding-left: var(--${prefix}--root-padding-left);`);
    lines.push('}');
  }

  lines.push('');
  return lines.join('\n');
}

function appendRootPaddingVars(
  lines: string[],
  padding: BaseStylesSpacingPadding,
  prefix: string,
  tokens: C2bConfig['tokens'],
): void {
  for (const side of PADDING_SIDES) {
    const value = padding[side];
    if (value === undefined) continue;
    const resolvedValue = resolveBaseStyleValueForScss(value, 'padding', prefix, tokens);
    lines.push(`  --${prefix}--root-padding-${side}: ${resolvedValue};`);
  }
}

function appendBlockGapVar(
  lines: string[],
  spacing: BaseStylesSpacing,
  prefix: string,
  tokens: C2bConfig['tokens'],
): void {
  if (!spacing.blockGap) return;
  const resolvedValue = resolveBaseStyleValueForScss(spacing.blockGap, 'blockGap', prefix, tokens);
  lines.push(`  --${prefix}--root-block-gap: ${resolvedValue};`);
}

/**
 * Block-gap utility rules mirroring WordPress layout behavior:
 * - constrained/flow layouts: reset all children's vertical margins, then
 *   apply margin-block-start to non-first siblings (lobotomized owl)
 * - flex/grid layouts: gap on the container
 *
 * The `> *` reset both kills browser default margins on h1–h6/p/etc. and
 * gives first-child elements `margin-block-start: 0` without needing a
 * separate `:first-child` rule.
 */
function appendBlockGapRules(lines: string[], prefix: string): void {
  lines.push('');
  lines.push(`:where(.is-layout-constrained) > * {`);
  lines.push(`  margin-block-start: 0;`);
  lines.push(`  margin-block-end: 0;`);
  lines.push('}');

  lines.push('');
  lines.push(`:where(.is-layout-constrained) > * + * {`);
  lines.push(`  margin-block-start: var(--${prefix}--root-block-gap);`);
  lines.push('}');

  lines.push('');
  lines.push(`:where(.is-layout-flex) {`);
  lines.push(`  gap: var(--${prefix}--root-block-gap);`);
  lines.push('}');

  lines.push('');
  lines.push(`:where(.is-layout-grid) {`);
  lines.push(`  gap: var(--${prefix}--root-block-gap);`);
  lines.push('}');
}

/**
 * Layout-constraint rules mirroring WordPress's constrained-layout behavior.
 * Default children clamp to contentSize; .alignwide overrides to wideSize.
 * Uses the same selectors and !important as WordPress for byte-identical results.
 */
function appendLayoutConstraintRules(
  lines: string[],
  prefix: string,
  tokens: C2bConfig['tokens'],
): void {
  const layoutTokens = tokens.layout;
  if (!layoutTokens) return;

  const hasContentSize = 'contentSize' in layoutTokens;
  const hasWideSize = 'wideSize' in layoutTokens;

  if (hasContentSize) {
    lines.push('');
    lines.push(`.is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {`);
    lines.push(`  max-width: var(--${prefix}--layout-content-size);`);
    lines.push(`  margin-left: auto !important;`);
    lines.push(`  margin-right: auto !important;`);
    lines.push('}');
  }

  if (hasWideSize) {
    lines.push('');
    lines.push(`.is-layout-constrained > .alignwide {`);
    lines.push(`  max-width: var(--${prefix}--layout-wide-size);`);
    lines.push(`  margin-left: auto !important;`);
    lines.push(`  margin-right: auto !important;`);
    lines.push('}');
  }
}
