import type { C2bConfig } from '../types.js';
import { CATEGORY_REGISTRY, CATEGORY_ORDER, DEFAULT_FLUID, camelToKebab, kebabToCamel } from '../types.js';
import { buildFluidClamp } from './fluid.js';

const VALID_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

// Wraps a token value in a single-quoted JS string literal. Values are raw CSS,
// and font stacks carry their own quotes ("'Inter Tight', system-ui"), which
// would close the literal early if they weren't escaped.
function quote(value: string): string {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

// Object keys that aren't valid identifiers — a purely numeric zIndex key like
// "100" — have to be quoted rather than emitted bare.
function emitKey(key: string): string {
  return VALID_IDENTIFIER.test(key) ? key : quote(key);
}

// Converts a token key to a valid camelCase JS identifier.
// Keys starting with digits (e.g. "2-x-small" → "2XSmall") are reordered
// so the leading digit follows the first letter: "2XSmall" → "x2Small".
function toJsIdentifier(key: string): string {
  // kebabToCamel only lifts a letter that follows a hyphen, so a hyphen sitting
  // before a digit ("source-serif-4") survives into the output. Drop those too.
  const camel = kebabToCamel(key).replace(/-+([0-9])/g, '$1');
  return camel.replace(/^(\d+)([A-Za-z])/, (_, digits, letter) => letter.toLowerCase() + digits);
}

export function generateTokensDts(config: C2bConfig): string {
  return [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
    `export declare const ${toJsIdentifier(config.prefix)}Tokens: Record<string, Record<string, string>>;`,
    `export default ${toJsIdentifier(config.prefix)}Tokens;`,
    '',
  ].join('\n');
}

export function generateTokensJs(config: C2bConfig): string {
  const lines: string[] = [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
    `export const ${toJsIdentifier(config.prefix)}Tokens = {`,
  ];

  type CatEntry = { jsKey: string; entries: Array<{ jsTokenKey: string; value: string }> };
  const populated: CatEntry[] = [];

  for (const category of CATEGORY_ORDER) {
    const group = config.tokens[category];
    if (!group) continue;

    const def = CATEGORY_REGISTRY[category];

    const jsKey = toJsIdentifier(def.cssSegment);
    const entries: CatEntry['entries'] = [];

    for (const [key, entry] of Object.entries(group)) {
      const value = (entry.fluid
        ? buildFluidClamp(entry, config.fluid ?? DEFAULT_FLUID)
        : null) ?? entry.value;
      entries.push({
        jsTokenKey: toJsIdentifier(key),
        value,
      });
    }

    if (entries.length > 0) {
      populated.push({ jsKey, entries });
    }
  }

  populated.forEach(({ jsKey, entries }, catIdx) => {
    const lastCat = catIdx === populated.length - 1;
    lines.push(`    ${emitKey(jsKey)}: {`);
    entries.forEach(({ jsTokenKey, value }, tokIdx) => {
      const lastTok = tokIdx === entries.length - 1;
      lines.push(`        ${emitKey(jsTokenKey)}: ${quote(value)}${lastTok ? '' : ','}`);
    });
    lines.push(`    }${lastCat ? '' : ','}`);
  });

  lines.push('};');
  lines.push('');
  lines.push(`export default ${toJsIdentifier(config.prefix)}Tokens;`);
  lines.push('');

  return lines.join('\n');
}
