import type { C2bConfig } from '../types.js';
import { CATEGORY_REGISTRY, CATEGORY_ORDER, camelToKebab } from '../types.js';
import { buildFluidClamp } from './fluid.js';

export function generateTokensWpCss(config: C2bConfig): string {
  const lines: string[] = [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
    ':root {',
  ];

  let firstCategory = true;

  for (const category of CATEGORY_ORDER) {
    const group = config.tokens[category];
    if (!group) continue;

    const def = CATEGORY_REGISTRY[category];

    if (!firstCategory) {
      lines.push('');
    }
    firstCategory = false;

    lines.push(`  /* ${def.label} */`);

    for (const [key, entry] of Object.entries(group)) {
      // Layout keys are camelCase in config but kebab-case in CSS variables
      const cssKey = def.directMap ? camelToKebab(key) : key;
      const varName = `--${config.prefix}--${def.cssSegment}-${cssKey}`;
      const fallback = entry.fluid ? buildFluidClamp(entry) ?? entry.value : entry.value;

      if (def.wpPreset && entry.slug) {
        lines.push(`  ${varName}: var(${def.wpPreset}--${entry.slug}, ${fallback});`);
      } else {
        lines.push(`  ${varName}: ${fallback};`);
      }
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
