import type { C2bConfig } from '../types.js';
import { CATEGORY_REGISTRY, CATEGORY_ORDER, DEFAULT_FLUID, camelToKebab } from '../types.js';
import { buildFluidClamp } from './fluid.js';

export function generateTokensScss(config: C2bConfig): string {
  const lines: string[] = [
    '// Auto-generated by component2block — do not edit manually',
  ];

  for (const category of CATEGORY_ORDER) {
    const group = config.tokens[category];
    if (!group) continue;

    const def = CATEGORY_REGISTRY[category];

    lines.push('');
    lines.push(`// ${def.label}`);

    for (const [key, entry] of Object.entries(group)) {
      const cssKey = def.directMap ? camelToKebab(key) : key;
      const varName = `$${config.prefix}-${def.cssSegment}-${cssKey}`;
      const clampValue = entry.fluid ? buildFluidClamp(entry, config.fluid ?? DEFAULT_FLUID) : null;
      lines.push(`${varName}: ${clampValue ?? entry.value};`);
    }
  }

  lines.push('');

  return lines.join('\n');
}
