import type { C2bConfig } from '../types.js';
import { CATEGORY_REGISTRY, CATEGORY_ORDER, DEFAULT_FLUID, camelToKebab, kebabToCamel } from '../types.js';
import { buildFluidClamp } from './fluid.js';

// Converts a token key to a valid camelCase JS identifier.
// Keys starting with digits (e.g. "2-x-small" → "2XSmall") are reordered
// so the leading digit follows the first letter: "2XSmall" → "x2Small".
function toJsIdentifier(key: string): string {
  const camel = kebabToCamel(key);
  return camel.replace(/^(\d+)([A-Za-z])/, (_, digits, letter) => letter.toLowerCase() + digits);
}

export function generateTokensDts(config: C2bConfig): string {
  return [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
    `export declare const ${config.prefix}Tokens: Record<string, Record<string, string>>;`,
    `export default ${config.prefix}Tokens;`,
    '',
  ].join('\n');
}

export function generateTokensJs(config: C2bConfig): string {
  const lines: string[] = [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
    `export const ${config.prefix}Tokens = {`,
  ];

  type CatEntry = { jsKey: string; entries: Array<{ jsTokenKey: string; value: string }> };
  const populated: CatEntry[] = [];

  for (const category of CATEGORY_ORDER) {
    const group = config.tokens[category];
    if (!group) continue;

    const def = CATEGORY_REGISTRY[category];
    if (def.scssOnly) continue;

    const jsKey = toJsIdentifier(def.cssSegment);
    const entries: CatEntry['entries'] = [];

    for (const [key, entry] of Object.entries(group)) {
      const value = (entry.fluid
        ? buildFluidClamp(entry, config.fluid ?? DEFAULT_FLUID)
        : null) ?? entry.value;
      entries.push({
        jsTokenKey: toJsIdentifier(key),
        value,
      });
    }

    if (entries.length > 0) {
      populated.push({ jsKey, entries });
    }
  }

  populated.forEach(({ jsKey, entries }, catIdx) => {
    const lastCat = catIdx === populated.length - 1;
    lines.push(`    ${jsKey}: {`);
    entries.forEach(({ jsTokenKey, value }, tokIdx) => {
      const lastTok = tokIdx === entries.length - 1;
      lines.push(`        ${jsTokenKey}: '${value}'${lastTok ? '' : ','}`);
    });
    lines.push(`    }${lastCat ? '' : ','}`);
  });

  lines.push('};');
  lines.push('');
  lines.push(`export default ${config.prefix}Tokens;`);
  lines.push('');

  return lines.join('\n');
}
