import type { C2bConfig } from '../types.js';
import { appendFlowSpacingRules, hasFlowSpacing } from './flow-spacing.js';

/**
 * Emit typography.css for the WordPress output directory.
 *
 * Contains the same flow-spacing rules as base-styles.scss (per-heading top
 * margin, after-heading tightening, list-item rhythm), but as plain CSS so a
 * block theme can enqueue it directly. References `var(--{prefix}--spacing-*)`
 * variables that tokens.css already defines in the same context.
 *
 * Returns null when no flow-spacing properties are configured — caller should
 * skip writing the file rather than emit an empty stylesheet.
 */
export function generateTypographyCss(config: C2bConfig): string | null {
  if (!hasFlowSpacing(config.baseStyles)) return null;

  const { baseStyles, prefix, tokens } = config;
  // baseStyles is non-undefined here because hasFlowSpacing returned true.
  const lines: string[] = [
    '/* Auto-generated by component2block — do not edit manually */',
  ];
  appendFlowSpacingRules(lines, baseStyles!, prefix, tokens);
  lines.push('');
  return lines.join('\n');
}
